/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.FbConnect;


/**
 *
 * @author zamama
 */
public class aceuil_admin1 extends javax.swing.JFrame {

    /**
     * Creates new form aceuil_admin
     */
    public aceuil_admin1() {
        initComponents();
    }
    
     public aceuil_admin1(String login,int id) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        GU = new javax.swing.JButton();
        GN = new javax.swing.JButton();
        GG = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GE = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dec = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GU.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        GU.setText("Gestion Utilisateur");
        getContentPane().add(GU, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 500, -1));

        GN.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        GN.setText("Gestion Newsletter");
        getContentPane().add(GN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 500, -1));

        GG.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        GG.setText("Consulter Liste Des  Guides");
        getContentPane().add(GG, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 500, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/graphics/bill-homme-personne-utilisateur-icone-6596-32.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 44));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/graphics/n.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 47, 33));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/graphics/phare-icone-7347-32.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 37, 30));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Espace Administrateur");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        GE.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        GE.setText("Gestion Experience");
        getContentPane().add(GE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 502, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/graphics/avion-sacs-icone-9251-32.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 38));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/graphics/deconnectez-vous-mon-profil-icone-5679-32.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, -1, 30));

        dec.setForeground(new java.awt.Color(204, 0, 0));
        dec.setText("Deconnexion");
        dec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decActionPerformed(evt);
            }
        });
        getContentPane().add(dec, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/graphics/10494570_711118602338461_8591650611456298261_n.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decActionPerformed
       this.setVisible(false); 
          //Authentification1 a = new Authentification1();
            //a.setVisible(true);
    }//GEN-LAST:event_decActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aceuil_admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aceuil_admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aceuil_admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aceuil_admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aceuil_admin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GE;
    private javax.swing.JButton GG;
    private javax.swing.JButton GN;
    private javax.swing.JButton GU;
    private javax.swing.JButton dec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
