/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

/**
 *
 * @author Samsung
 */
public class Acc_Exp extends javax.swing.JFrame {
  private int id;
  String login;
    /**
     * Creates new form Acc_Exp
     */
    public Acc_Exp() {
        initComponents();
    }
 
     public Acc_Exp(int id) {
        this.id=id;
         initComponents();
      
    }
          public Acc_Exp(int id,String login) {
        this.id=id;
        this.login=login;
         initComponents();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nouv_exp = new javax.swing.JButton();
        ExpExist = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nouv_exp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nouv_exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/ajouter-en-plus-icone-9315-48.png"))); // NOI18N
        nouv_exp.setText("Nouvelle Expérience");
        nouv_exp.setContentAreaFilled(false);
        nouv_exp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nouv_expMouseClicked(evt);
            }
        });
        getContentPane().add(nouv_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 210, 50));

        ExpExist.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ExpExist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Preview-icon.png"))); // NOI18N
        ExpExist.setText("Expérience Existantes");
        ExpExist.setContentAreaFilled(false);
        ExpExist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpExistMouseClicked(evt);
            }
        });
        getContentPane().add(ExpExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/tt.jpg"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nouv_expMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nouv_expMouseClicked
        System.out.println(id);
        AjoutNouvelleExp nouvExp=new AjoutNouvelleExp(id);
       nouvExp.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_nouv_expMouseClicked

    private void ExpExistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpExistMouseClicked
        AfficheExperience affiche=new AfficheExperience(id);
        affiche.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ExpExistMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       AccueilUtilisateur acc=new AccueilUtilisateur(id);
       this.setVisible(false);
       acc.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acc_Exp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acc_Exp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acc_Exp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acc_Exp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acc_Exp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExpExist;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nouv_exp;
    // End of variables declaration//GEN-END:variables
}
