/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Compagnie;
import edu.esprit.dao.entities.Lieu;
import edu.esprit.dao.implementations.CompagnieDAO;
import edu.esprit.dao.implementations.LieuDAO;
import edu.esprit.dao.technique.MyConnection;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author esprit
 */
public class AffichageLieu extends javax.swing.JFrame {
private Connection connection;
    /**
     * Creates new form AffichageLieu
     */
    public AffichageLieu() {
        initComponents();
        try {
            connection = MyConnection.getInstance();
        } catch (IOException ex) {
            Logger.getLogger(AffichageLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        quitterButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new MyTableLieuModel());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 600, 170));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Affichage des lieux");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 222, 75));

        quitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        quitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Button-Close-icon.png"))); // NOI18N
        quitterButton.setText("Quitter");
        quitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitterButtonMouseClicked(evt);
            }
        });
        getContentPane().add(quitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/pie-chart-icon.png"))); // NOI18N
        jButton1.setText("Pie Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/BestBack.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           try {
            LieuDAO lieuDAO = new LieuDAO();
            List<Lieu> lieux = lieuDAO.afficherLieu();
            
            /* try {
            String requete="select Nom,Nombre from recommandation";
            JDBCCategoryDataset dataset=new JDBCCategoryDataset(MyConnection.getInstance(), requete);
            JFreeChart chart=ChartFactory.createLineChart("Query chart", "Nombre", "Nom", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer=null;
            CategoryPlot plot=null;
            renderer=new BarRenderer();
            ChartFrame frame=new ChartFrame("Query chart",chart);
            frame.setVisible(true);
            frame.setSize(400,650);
            
            } catch (SQLException ex) {
            Logger.getLogger(AffichageCompagnie.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
            Logger.getLogger(AffichageCompagnie.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            DefaultPieDataset data = new DefaultPieDataset();
            for (Lieu lieu:lieux) {
                String adresse = lieu.getAdresse();
                data.setValue(adresse, lieu.getNombre());
            }
// create a chart with the dataset
            //JFreeChart chart = ChartFactory.createPieChart3D("Compagnie chart", data, true, true, true);
            JFreeChart chart = ChartFactory.createPieChart3D("Compagnie chart", data, true, true, true);
            chart.createBufferedImage(500, 220);
            final PiePlot plot = ( PiePlot ) chart.getPlot( );
            plot.setStartAngle( 270 );
            plot.setForegroundAlpha( 0.60f );
            plot.setInteriorGap( 0.02 );
            int width = 640; /* Width of the image */
            int height = 480; /* Height of the image */
            File pieChart3D = new File( "pie_Chart3D.jpeg" );
            ChartUtilities.saveChartAsJPEG( pieChart3D , chart , width , height );  
            Desktop.getDesktop().open(pieChart3D);
        } catch (IOException ex) {
            Logger.getLogger(AffichageCompagnie.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void quitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterButtonMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MenuRecommandation m=new MenuRecommandation();
        m.setVisible(true);
    }//GEN-LAST:event_quitterButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichageLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichageLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichageLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichageLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffichageLieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton quitterButton;
    // End of variables declaration//GEN-END:variables
}
