/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Compagnie;
import edu.esprit.dao.implementations.AdministrateurDAO;
import edu.esprit.dao.implementations.CompagnieDAO;
import edu.esprit.dao.technique.MyConnection;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author esprit
 */
public class AffichageCompagnie extends javax.swing.JFrame {

    private Connection connection;
   int id;
   String login;
    /**
     * Creates new form AffichageRecommandation
     */
    public AffichageCompagnie() {
        initComponents();
        try {
            connection = MyConnection.getInstance();
        } catch (IOException ex) {
            Logger.getLogger(AffichageCompagnie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public AffichageCompagnie(String login,int id) {
        this.login=login;
        this.id=id;
        initComponents();
        try {
            connection = MyConnection.getInstance();
        } catch (IOException ex) {
            Logger.getLogger(AffichageCompagnie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        quitterButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1063, 737));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new MyTableCompagnieModel());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 660, 180));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Affichage Des Compagnies");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 33));

        quitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        quitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        quitterButton.setContentAreaFilled(false);
        quitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitterButtonMouseClicked(evt);
            }
        });
        getContentPane().add(quitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, -1, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/pie-chart-icon.png"))); // NOI18N
        jButton1.setText("Pie Chart");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, 120, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1063, 737));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1080, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterButtonMouseClicked
        this.setVisible(false);
        //MenuRecommandation m=new MenuRecommandation();
        AccueilAdmin m= new AccueilAdmin(login,id);
        m.setVisible(true);  
    }//GEN-LAST:event_quitterButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            CompagnieDAO compagnieDAO = new CompagnieDAO();
            List<Compagnie> compagnies = compagnieDAO.afficherCompagnies();
            
            /* try {
            String requete="select Nom,Nombre from recommandation";
            JDBCCategoryDataset dataset=new JDBCCategoryDataset(MyConnection.getInstance(), requete);
            JFreeChart chart=ChartFactory.createLineChart("Query chart", "Nombre", "Nom", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer renderer=null;
            CategoryPlot plot=null;
            renderer=new BarRenderer();
            ChartFrame frame=new ChartFrame("Query chart",chart);
            frame.setVisible(true);
            frame.setSize(400,650);
            
            } catch (SQLException ex) {
            Logger.getLogger(AffichageCompagnie.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
            Logger.getLogger(AffichageCompagnie.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            DefaultPieDataset data = new DefaultPieDataset();
            for (Compagnie compagnie : compagnies) {
                String nom = compagnie.getNom();
                data.setValue(nom, compagnie.getNombre());
            }
// create a chart with the dataset
            //JFreeChart chart = ChartFactory.createPieChart3D("Compagnie chart", data, true, true, true);
            JFreeChart chart = ChartFactory.createPieChart("Compagnie chart", data, true, true, true);
            chart.createBufferedImage(500, 220);
            final PiePlot plot = ( PiePlot ) chart.getPlot( );
          /*  plot.setStartAngle( 270 );
            plot.setForegroundAlpha( 0.60f );
            plot.setInteriorGap( 0.02 );*/
            int width = 640; /* Width of the image */
            int height = 480; /* Height of the image */
            File pieChart3D = new File( "pie_Chart3D.jpeg" );
            ChartUtilities.saveChartAsJPEG( pieChart3D , chart , width , height );  
            Desktop.getDesktop().open(pieChart3D);
        } catch (IOException ex) {
            Logger.getLogger(AffichageCompagnie.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichageCompagnie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichageCompagnie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichageCompagnie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichageCompagnie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffichageCompagnie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton quitterButton;
    // End of variables declaration//GEN-END:variables
}
