/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.implementations.ExperiencesDAO;
import edu.esprit.dao.entities.Experience;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JSlider;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.binding.LibVlcConst;
import uk.co.caprica.vlcj.discovery.NativeDiscovery;
//import uk.co.caprica.vlcj.player.MediaPlayer;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;
import edu.esprit.dao.MediaPlayer.MediaPlayer;
/**
 *
 * @author Samsung
 */
public class AffichagesDetailExperience extends javax.swing.JFrame {

    int id_experience;
    int id_utilsateur;
    private JList list;

    /**
     * Creates new form AffichagesDetailExperience
     */
    public AffichagesDetailExperience() {
        initComponents();
    }

    public AffichagesDetailExperience(int id_experience,int id_utilsateur) {

        this.id_experience = id_experience;
        this.id_utilsateur = id_utilsateur;
        ExperiencesDAO expDAO = new ExperiencesDAO();
        Experience exp = new Experience();
        exp = expDAO.cherchExperienceById(this.id_experience);

        initComponents();
        date.setEnabled(false);
        //date.getEditor().setEnabled(false);
        contenu.setText(exp.getContenu());
        date.setValue(exp.convtoDate(exp.getDate()));
        dep.setValue(exp.getDepense());
        titre_exp.setText(exp.getTitre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        contenu = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        vid = new javax.swing.JList();
        jScrollPane5 = new javax.swing.JScrollPane();
        photo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        titre_exp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        date = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        dep = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ph = new javax.swing.JList();
        play = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Texte");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, 30));

        jTable1.setModel(new MyTableTexteModel(this.id_experience));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 400, 80));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Video");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Photos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 60, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        contenu.setEditable(false);
        contenu.setColumns(20);
        contenu.setRows(5);
        jScrollPane4.setViewportView(contenu);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 280, 80));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 60, 50));

        vid.setModel(new VideoListeModel(this.id_experience));
        vid.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                vidValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(vid);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 120, 190));

        jScrollPane5.setViewportView(photo);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 230, 190));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Titre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 40, 20));

        titre_exp.setEditable(false);
        titre_exp.setBackground(new java.awt.Color(255, 255, 255));
        titre_exp.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(titre_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 280, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, -1));

        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        date.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.MONTH));
        date.setEnabled(false);
        date.setOpaque(false);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 170, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Dépense");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 70, 20));

        dep.setEditable(false);
        dep.setBackground(new java.awt.Color(255, 255, 255));
        dep.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dep.setDoubleBuffered(true);
        getContentPane().add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 160, 30));

        ph.setModel(new listeModel(this.id_experience));
        ph.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                phValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ph);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 100, 190));

        play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/play-arrow-then-right-icone-9610-64.png"))); // NOI18N
        play.setText("Jouer");
        play.setContentAreaFilled(false);
        play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playActionPerformed(evt);
            }
        });
        getContentPane().add(play, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 160, 90));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 910, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 920, 10));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel10.setText("Détail Expérience");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 310, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        MenuChoixExperience affiche = new MenuChoixExperience(id_experience,id_utilsateur);
        affiche.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void vidValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_vidValueChanged

    }//GEN-LAST:event_vidValueChanged

    private void playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playActionPerformed
        final MediaPlayer mpu;
        NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "C:/Program Files/VideoLAN/VLC");
        Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
        new NativeDiscovery().discover();
//        UIManager.put("Slider bagkrgound",1);
//        UIManager.put("Slider.background",1);
        mpu = new MediaPlayer();

        JButton play_btn = new JButton("play");
        JButton stop_btn = new JButton("stop");
        JButton foward_btn = new JButton(">>");
        foward_btn.setToolTipText("foward");
        JButton rewind_btn = new JButton("<<");
        rewind_btn.setToolTipText("rewind");
        JButton fullscreen_btn = new JButton("enlarge");

        JSlider timeline = new JSlider(0, 100, 0);
        timeline.setMajorTickSpacing(10);
        timeline.setMajorTickSpacing(5);
        timeline.setPaintTicks(true);
        timeline.setPreferredSize(new Dimension(550, 30));
        timeline.setToolTipText("slide to media position");

        JSlider volume_sld = new JSlider(0, 100, 100);
        volume_sld.setOrientation(JSlider.HORIZONTAL);
        volume_sld.setMinimum(LibVlcConst.MIN_VOLUME);
        volume_sld.setMaximum(LibVlcConst.MAX_VOLUME);
        volume_sld.setPaintTicks(true);
        volume_sld.setPreferredSize(new Dimension(100, 40));
        volume_sld.setToolTipText("Change volume");

        JLabel time_lbl = new JLabel("hh:mm:ss");
        JLabel video_length_lbl = new JLabel("---");
        JLabel lbl_video_title = new JLabel("Video Title:");
        JLabel lbl_date_uploaded = new JLabel("Date Uploaded:");
        JLabel lbl_video_description = new JLabel("Description:");
        JLabel video_title_lbl = new JLabel("---");
        JLabel date_uploaded_lbl = new JLabel("---");
        JLabel video_description_lbl = new JLabel("---");
        time_lbl = new JLabel("hh:mm:ss");

        JPanel timeline_pnl = new JPanel();
        timeline_pnl.setLayout(new FlowLayout(FlowLayout.CENTER));
        timeline_pnl.add(time_lbl);
        timeline_pnl.add(timeline);
        timeline_pnl.add(video_length_lbl);

        JPanel control_pnl = new JPanel();

        control_pnl.setLayout(new FlowLayout(FlowLayout.CENTER));
        control_pnl.add(volume_sld);
        control_pnl.add(play_btn);
        control_pnl.add(stop_btn);
        control_pnl.add(rewind_btn);
        control_pnl.add(foward_btn);
        control_pnl.add(fullscreen_btn);

        JPanel player_control_pnl = new JPanel();
        player_control_pnl.setLayout(new BorderLayout());
        player_control_pnl.add(timeline_pnl, BorderLayout.NORTH);
        player_control_pnl.add(control_pnl, BorderLayout.SOUTH);

        player_control_pnl = new JPanel();
        player_control_pnl.setLayout(new BorderLayout());
        player_control_pnl.add(timeline_pnl, BorderLayout.NORTH);
        player_control_pnl.add(control_pnl, BorderLayout.SOUTH);

        JPanel info_pnl = new JPanel();
        info_pnl.setLayout(new GridLayout(4, 2, 4, 4));
        info_pnl.add(lbl_video_title);
        info_pnl.add(video_title_lbl);
        info_pnl.add(lbl_date_uploaded);
        info_pnl.add(date_uploaded_lbl);
        info_pnl.add(lbl_video_description);
        info_pnl.add(video_description_lbl);

        JPanel bottom_pnl = new JPanel();
        bottom_pnl.setLayout(new FlowLayout(FlowLayout.LEFT));
        bottom_pnl.add(info_pnl);
        
        final JDialog frame = new JDialog(this, "Reproductor Multimedia");
        frame.add(mpu, BorderLayout.CENTER);
        frame.add(player_control_pnl, BorderLayout.SOUTH);
        mpu.getMediaPlayer().setStandardMediaOptions();
        frame.setSize(500, 500);
        frame.setLocation(50, 50);
        frame.setVisible(true);
       
        mpu.getMediaPlayer().playMedia(VideoListeModel.chemin);
        mpu.getMediaPlayer().addMediaPlayerEventListener(mpu);
        mpu.getMediaPlayer().addMediaPlayerEventListener(mpu);

        frame.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                mpu.getMediaPlayer().stop();
                frame.dispose();
            }
        });

        System.out.println(VideoListeModel.chemin);

    }//GEN-LAST:event_playActionPerformed

    private void phValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_phValueChanged
//        ImageIcon icon = createImageIcon(listeModel.chemin);
        ImageIcon icon = new ImageIcon(listeModel.chemin);
//
//        photo.setIcon(icon);
//        photo.setIcon(icon);
//        if  (icon != null) {
//            photo.setText(null);
//        } else {
//            photo.setText("Image not found");
//        }
//        photo.setEnabled(true);
//        photo.setDisabledIcon(icon);

        Image img = icon.getImage();
        //Image newimg = img.getScaledInstance(photo., 310,  java.awt.Image.SCALE_SMOOTH);
        Image newimg = img.getScaledInstance(photo.getWidth(), photo.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon newIcon = new ImageIcon(newimg);
        photo.setIcon(newIcon);
        photo.setEnabled(true);
        photo.setDisabledIcon(newIcon);    }//GEN-LAST:event_phValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichagesDetailExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichagesDetailExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichagesDetailExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichagesDetailExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffichagesDetailExperience().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contenu;
    private javax.swing.JSpinner date;
    private javax.swing.JFormattedTextField dep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JList ph;
    private javax.swing.JLabel photo;
    private javax.swing.JButton play;
    private javax.swing.JTextField titre_exp;
    private javax.swing.JList vid;
    // End of variables declaration//GEN-END:variables
}
