/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.UtilisateurDAO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author esprit
 */
public class AffichageUtilisateur extends javax.swing.JFrame {

    /**
     * Creates new form AffichageUtilisateur
     */
    public AffichageUtilisateur() {
        initComponents();
        UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
        Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurByLogin((String) jTable1.getValueAt(0,3));
        ImageIcon image = new ImageIcon(utilisateur.getImage());
        imageLabel.setIcon(image);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        retourButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new edu.esprit.dao.graphics.MyTableUtilisateurModel());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 480, 171));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Affichage Des Utilisateurs");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        retourButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        retourButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        retourButton.setContentAreaFilled(false);
        retourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourButtonMouseClicked(evt);
            }
        });
        getContentPane().add(retourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, -1, -1));
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 120, 170));

        loginField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        getContentPane().add(loginField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 110, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1063, 737));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourButtonMouseClicked
         this.setVisible(false);
         MenuUtilisateur m = new MenuUtilisateur();
          m.setVisible(true);
    }//GEN-LAST:event_retourButtonMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       // JOptionPane.showMessageDialog(this,jTable1.getValueAt(jTable1.getSelectedRow(),3));
        
        UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
        Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurByLogin((String) jTable1.getValueAt(jTable1.getSelectedRow(),3));
        ImageIcon image = new ImageIcon(utilisateur.getImage());
        imageLabel.setIcon(image);
        loginField.setText(utilisateur.getLogin());
//        jTable1.getSelectedRow()
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AffichageUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AffichageUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AffichageUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AffichageUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AffichageUtilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel loginField;
    private javax.swing.JButton retourButton;
    // End of variables declaration//GEN-END:variables
}
