/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Sujet;
import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.SujetDAO;
import edu.esprit.dao.implementations.UtilisateurDAO;

/**
 *
 * @author Toch
 */
public class AjoutSujet extends javax.swing.JFrame {

    String login;
    int id;
    /**
     * Creates new form AjoutSujet
     */
    public AjoutSujet() {
        initComponents();
    }
    
    public AjoutSujet(String login,int id) {
        initComponents();
        this.login=login;
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitreLabel = new javax.swing.JLabel();
        TitreSujet = new javax.swing.JLabel();
        TSujet = new javax.swing.JTextField();
        TextLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        ModifierButton = new javax.swing.JButton();
        SupprimerButton = new javax.swing.JButton();
        AjouterButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitreLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        TitreLabel.setText("Ajout Sujet");
        getContentPane().add(TitreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        TitreSujet.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TitreSujet.setText("Titre");
        getContentPane().add(TitreSujet, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 60, -1));
        getContentPane().add(TSujet, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 330, 30));

        TextLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TextLabel.setText("Text");
        getContentPane().add(TextLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        TText.setColumns(20);
        TText.setRows(5);
        jScrollPane1.setViewportView(TText);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 430, 140));

        Table.setModel(new MyTableSujetModel());
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 670, 130));

        ModifierButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ModifierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/modifier.png"))); // NOI18N
        ModifierButton.setText("Modifier");
        ModifierButton.setContentAreaFilled(false);
        ModifierButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ModifierButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ModifierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 650, 150, -1));

        SupprimerButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SupprimerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/supprimer.png"))); // NOI18N
        SupprimerButton.setText("Supprimer");
        SupprimerButton.setContentAreaFilled(false);
        SupprimerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupprimerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(SupprimerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, -1, -1));

        AjouterButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        AjouterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/ajouter-en-plus-icone-9315-48_1.png"))); // NOI18N
        AjouterButton.setText("Ajouter");
        AjouterButton.setContentAreaFilled(false);
        AjouterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjouterButtonMouseClicked(evt);
            }
        });
        getContentPane().add(AjouterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 650, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifierButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierButtonMouseClicked
       String sujet = TSujet.getText();
       String sujet1 = TText.getText();
       
       SujetDAO sdao = new SujetDAO();
       int id=sdao.recupererId(sujet);
       UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
       Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurById(id);
       Sujet s= new Sujet(id,sujet,sujet1,utilisateur);
      
       sdao.modifierSujet(s);
        
        //LMessage2.setText("");
        MyTableSujetModel model = (MyTableSujetModel) Table.getModel();
        if(Table.getSelectedRow()==-1){
            if(Table.getRowCount()==0){
                
           }else {
               // LMessage2.setText("vous devez selectionner un sujet");
            }
        }else{
            model.setValueAt(TSujet.getText(), Table.getSelectedRow(), 0);
            model.setValueAt(TText.getText(), Table.getSelectedRow(), 1);
            //LMessage3.setText("Le sujet est modifier");
             this.setVisible(false); 
           AjoutSujet a = new AjoutSujet();
            a.setVisible(true);
            
            
        }
    }//GEN-LAST:event_ModifierButtonMouseClicked

    private void AjouterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterButtonMouseClicked
       String sujet = TSujet.getText();
       String sujet1 = TText.getText();
       UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
       Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurById(id);
       Sujet s  = new Sujet(sujet,sujet1,utilisateur);

       SujetDAO sdao = new SujetDAO();
        //System.out.println(s);
       sdao.ajouterSujet(s);
        this.setVisible(false); 
            AjoutSujet a = new AjoutSujet(login,id);
            a.setVisible(true);
        
        //LMessage.setText("Vous devez ajouter un nom de sujet");
    }//GEN-LAST:event_AjouterButtonMouseClicked

    private void SupprimerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimerButtonMouseClicked
        String sujet = TSujet.getText();
       String sujet1 = TText.getText();
       SujetDAO sdao = new SujetDAO();
       int id=sdao.recupererId(sujet);
       Sujet s=new Sujet(sujet,sujet1);
      
       sdao.supprimerSujet(id);
        
        //LMessage2.setText("");
        MyTableSujetModel model = (MyTableSujetModel) Table.getModel();
        if(Table.getSelectedRow()==-1){
            if(Table.getRowCount()==0){
                
            }else {
                //LMessage2.setText("Vous devez selectionner un sujet");
            }
        }else{
            //model.removeRow(Table.getSelectedRow());
            //LMessage3.setText("Le sujet est supprimer");
            this.setVisible(false); 
           AjoutSujet a = new AjoutSujet();
            a.setVisible(true);
            
            
        }
    }//GEN-LAST:event_SupprimerButtonMouseClicked

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        MyTableSujetModel model= (MyTableSujetModel) Table.getModel();
       TSujet.setText(model.getValueAt(Table.getSelectedRow(), 0).toString());
       TText.setText(model.getValueAt(Table.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutSujet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterButton;
    private javax.swing.JButton ModifierButton;
    private javax.swing.JButton SupprimerButton;
    private javax.swing.JTextField TSujet;
    private javax.swing.JTextArea TText;
    private javax.swing.JTable Table;
    private javax.swing.JLabel TextLabel;
    private javax.swing.JLabel TitreLabel;
    private javax.swing.JLabel TitreSujet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
