/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.implementations.ExperiencesDAO;
import edu.esprit.dao.implementations.VideoDAO;
import edu.esprit.dao.entities.Experience;
import edu.esprit.dao.entities.Photo;
import edu.esprit.dao.entities.Video;
import edu.esprit.dao.entities.Texte;
import edu.esprit.dao.implementations.PhotoDAO;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Samsung
 */
public class AjoutMedia extends javax.swing.JFrame {

    int id_experience;
    int id_utilsateur;
    private File imageUpload;
    private File videoUpload;
    Video vid = new Video();
    Photo ph = new Photo();
    Texte tx = new Texte();

    /**
     * Creates new form AjoutMedia
     */
    public AjoutMedia() {
        initComponents();
    }

    public AjoutMedia(int id_experience, int id_utilsateur) {
        this.id_experience = id_experience;
        this.id_utilsateur = id_utilsateur;

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        disp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        retour = new javax.swing.JLabel();
        ajout = new javax.swing.JButton();
        ds = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        chooservid = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descvid = new javax.swing.JTextArea();
        nomVid = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        Vidnom = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textCont = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 230, 190));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Photo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 50, 30));

        jButton1.setText("choisir fichier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Description");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
        });
        getContentPane().add(retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 640, 60, 60));

        ajout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/ajouter-en-plus-icone-9315-48.png"))); // NOI18N
        ajout.setText("Ajouter");
        ajout.setContentAreaFilled(false);
        ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutMouseClicked(evt);
            }
        });
        getContentPane().add(ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 140, 50));
        getContentPane().add(ds, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, 330, 90));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 10, 390));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("video");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        chooservid.setText("choisir fichier");
        chooservid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooservidMouseClicked(evt);
            }
        });
        getContentPane().add(chooservid, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, -1, -1));

        descvid.setColumns(20);
        descvid.setRows(5);
        jScrollPane1.setViewportView(descvid);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 300, 90));
        getContentPane().add(nomVid, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 770, 10));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Texte");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, -1));
        getContentPane().add(Vidnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 150, 20));

        textCont.setColumns(20);
        textCont.setRows(5);
        jScrollPane3.setViewportView(textCont);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 590, 60));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setText("Ajouter Des Détails");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ExperiencesDAO expDAO = new ExperiencesDAO();
        Experience exp;
        exp = expDAO.cherchExperienceById(this.id_experience);
        JFileChooser shooser = new JFileChooser();
        ImageFilter filtre = new ImageFilter();
        shooser.setFileFilter(filtre);
        shooser.setAcceptAllFileFilterUsed(false);
        shooser.showOpenDialog(null);
        imageUpload = shooser.getSelectedFile();

        Image img = Toolkit.getDefaultToolkit().getImage(imageUpload.getAbsolutePath());
        //Image img = Toolkit.getDefaultToolkit().getImage(imageUpload.getName());
        System.out.println(imageUpload.getName());
        Image newimg = img.getScaledInstance(disp.getWidth(), disp.getHeight(), java.awt.Image.SCALE_SMOOTH);

        ImageIcon newIcon = new ImageIcon(newimg);
        disp.setIcon(newIcon);
        disp.setEnabled(true);

        disp.setDisabledIcon(newIcon);
        disp.setVisible(true);
        String source = imageUpload.getAbsolutePath();
        int taille = (int) imageUpload.length();
        //String description=ds.getText();

        this.ph = new Photo(null, taille, source, exp);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
        MenuChoixExperience affiche = new MenuChoixExperience(id_experience, id_utilsateur);
        affiche.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_retourMouseClicked

    private void ajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutMouseClicked
        ExperiencesDAO expDAO = new ExperiencesDAO();
        Experience exp;
        exp = expDAO.cherchExperienceById(this.id_experience);
        String d = ds.getText();
        String dvid = descvid.getText();
        String cont = textCont.getText();

        this.tx.setContenu(cont);
        this.tx.setExp(exp);
        this.vid.setExtension(d);
        this.ph.setDescription(dvid);
        VideoDAO vidDAO = new VideoDAO();
        vidDAO.ajouterVideo(vid);

        PhotoDAO phDAO = new PhotoDAO();
        phDAO.ajouterPhoto(ph);

        JOptionPane.showMessageDialog(rootPane, "Ajout Effectué");

        disp.setVisible(false);
        ds.setText(null);
        descvid.setText(null);
    }//GEN-LAST:event_ajoutMouseClicked

    private void chooservidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooservidMouseClicked
        ExperiencesDAO expDAO = new ExperiencesDAO();
        Experience exp;
        exp = expDAO.cherchExperienceById(this.id_experience);
        JFileChooser shooser = new JFileChooser();
        VideoFilter filtre = new VideoFilter();
        shooser.setFileFilter(filtre);
        shooser.setAcceptAllFileFilterUsed(false);
        shooser.showOpenDialog(null);
        videoUpload = shooser.getSelectedFile();
        String source = videoUpload.getAbsolutePath();
        nomVid.setText(videoUpload.getName());
        int taille = (int) videoUpload.length();

        this.vid = new Video(null, taille, source, exp);
    }//GEN-LAST:event_chooservidMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Vidnom;
    private javax.swing.JButton ajout;
    private javax.swing.JButton chooservid;
    private javax.swing.JTextArea descvid;
    private javax.swing.JLabel disp;
    private javax.swing.JTextField ds;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nomVid;
    private javax.swing.JLabel retour;
    private javax.swing.JTextArea textCont;
    // End of variables declaration//GEN-END:variables
}
