/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.UtilisateurDAO;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author esprit
 */
public class AjoutUtilisateur extends javax.swing.JFrame {
public String myPath="";
public String monchemin="";
    /**
     * Creates new form AjoutUtilisateur
     */
    public AjoutUtilisateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        varNom = new javax.swing.JLabel();
        NomEdit = new javax.swing.JTextField();
        varPrenom = new javax.swing.JLabel();
        PrenomEdit = new javax.swing.JTextField();
        varMail = new javax.swing.JLabel();
        EmailEdit = new javax.swing.JTextField();
        varLogin = new javax.swing.JLabel();
        LoginEdit = new javax.swing.JTextField();
        varPassword = new javax.swing.JLabel();
        PasswordEdit = new javax.swing.JPasswordField();
        varAge = new javax.swing.JLabel();
        AgeEdit = new javax.swing.JTextField();
        AjoutButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        chemin = new javax.swing.JLabel();
        cheminLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Créer un compte");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 320, -1));

        varNom.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varNom.setText("Nom");
        getContentPane().add(varNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 77, -1));

        NomEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomEditKeyPressed(evt);
            }
        });
        getContentPane().add(NomEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 219, -1));

        varPrenom.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varPrenom.setText("Prenom");
        getContentPane().add(varPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 77, -1));

        PrenomEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrenomEditKeyPressed(evt);
            }
        });
        getContentPane().add(PrenomEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 219, -1));

        varMail.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varMail.setText("Email");
        getContentPane().add(varMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 77, -1));

        EmailEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailEditFocusLost(evt);
            }
        });
        getContentPane().add(EmailEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 219, -1));

        varLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varLogin.setText("Login");
        getContentPane().add(varLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 77, -1));

        LoginEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginEditKeyPressed(evt);
            }
        });
        getContentPane().add(LoginEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 219, -1));

        varPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varPassword.setText("Password");
        getContentPane().add(varPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 86, -1));

        PasswordEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordEditFocusLost(evt);
            }
        });
        getContentPane().add(PasswordEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 219, -1));

        varAge.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varAge.setText("Age");
        getContentPane().add(varAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 74, -1));

        AgeEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AgeEditKeyPressed(evt);
            }
        });
        getContentPane().add(AgeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 50, -1));

        AjoutButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        AjoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Button-Add-icon (1).png"))); // NOI18N
        AjoutButton.setText("Valider");
        AjoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjoutButtonMouseClicked(evt);
            }
        });
        getContentPane().add(AjoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 690, -1, -1));

        ResetButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Button-Refresh-icon.png"))); // NOI18N
        ResetButton.setText("Réinitialiser");
        ResetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, 140, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Choisissez une photo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 150, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("Choisir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 100, -1));
        getContentPane().add(chemin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 140, 150));

        cheminLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        getContentPane().add(cheminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 570, 180, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 650, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1063, 737));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjoutButtonMouseClicked
          String nom=NomEdit.getText();
          String prenom=PrenomEdit.getText();
          String email=EmailEdit.getText();
          String login=LoginEdit.getText();
          String password=PasswordEdit.getText();
         int age = Integer.parseInt(AgeEdit.getText());
        // String nomImage=f.getAbsolutePath();
        Utilisateur utilisateur=new Utilisateur(nom,prenom,email,login,password,age,monchemin);
       UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
       if( utilisateurDAO.ajouterUtilisateur(utilisateur))
        JOptionPane.showMessageDialog(rootPane,"ajout effectué");
       else 
         JOptionPane.showMessageDialog(rootPane,"ajout non effectué");  
       
        this.setVisible(false);
        Authentification m=new Authentification();
        m.setVisible(true);
       
    }//GEN-LAST:event_AjoutButtonMouseClicked

    private void ResetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetButtonMouseClicked
         NomEdit.setText("");
         PrenomEdit.setText("");
         EmailEdit.setText("");
         LoginEdit.setText("");
         PasswordEdit.setText("");
         AgeEdit.setText("");
        // chemin.setText(null);
    }//GEN-LAST:event_ResetButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               
        int o=jFileChooser1.showOpenDialog(this);
        if(o==JFileChooser.APPROVE_OPTION)
        {
            File file=jFileChooser1.getSelectedFile();
            ImageIcon myImage = new ImageIcon(""+file);
            myPath=file.getAbsolutePath();
            System.out.println(myPath);
            monchemin=file.getName();
            chemin.setSize(myImage.getIconHeight(),myImage.getIconWidth());
            //chemin.setIcon(myImage);
            cheminLabel.setText(monchemin);
        }
            
            /*
            
              if(o==JFileChooser.APPROVE_OPTION)
        {
            File file=jFileChooser1.getSelectedFile();
            try {
                //            ImageIcon myImage = new ImageIcon(""+file);
//            myPath=file.getAbsolutePath();
//            chemin.setSize(myImage.getIconHeight(),myImage.getIconWidth());
//            chemin.setIcon(myImage);
                Image image = ImageIO.read(file);
                
            } catch (IOException ex) {
                Logger.getLogger(AjoutUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
            }
            */
       /* JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        String nomImage=f.getAbsolutePath();
        //chemin.setText(nomImage);
       // String filename=f.getName();
        //ImageIcon icon1 = (ImageIcon) chemin.getIcon();
        //chemin.setText(filename);
        //chemin.setIcon(icon1);*/
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AgeEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeEditKeyPressed
      char car= evt.getKeyChar();
        if((car<'0' || car>'9' ) && AgeEdit.getText().contains(".")
            && (car!=(char)KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulment des chiffres","validation  "
                ,JOptionPane.INFORMATION_MESSAGE);
        } else if
        ((car<'0' ||car>'9')&&(car!='.')
            &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null,"SVP entrer seulement des chiffres","message de confirmation d'ecrire seulment des chiffres "
                ,JOptionPane.INFORMATION_MESSAGE); }
        
    }//GEN-LAST:event_AgeEditKeyPressed

    private void NomEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomEditKeyPressed
        char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettres sont acceptées ","validation d'accepter des lettres"
                ,JOptionPane.INFORMATION_MESSAGE);
    }                              
    }//GEN-LAST:event_NomEditKeyPressed
    public boolean isEmail(String chaine)
    {Pattern pat=null;
     Matcher mat=null;    
    pat=Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
    mat=pat.matcher(chaine);
    if(mat.find())
    {
        return true;
    }
    else 
    {
        return false;
    }
    }
    
    private void EmailEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailEditFocusLost
       if(isEmail(EmailEdit.getText()))
       {
           
       }
       else
       {
           JOptionPane.showMessageDialog(null, "Email incorrecte","veuillez entrer un mail valide",JOptionPane.INFORMATION_MESSAGE);
           EmailEdit.requestFocus();
       }
    }//GEN-LAST:event_EmailEditFocusLost

    private void PrenomEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrenomEditKeyPressed
        char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettres sont acceptées ","validation d'accepter des lettres"
                ,JOptionPane.INFORMATION_MESSAGE);
    } 
    }//GEN-LAST:event_PrenomEditKeyPressed

    private void LoginEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginEditKeyPressed
     char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettres qui sont acceptées ","validation d'accepter des lettres"
                ,JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_LoginEditKeyPressed

    private void PasswordEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordEditFocusLost
    if(PasswordEdit.getPassword().length >=8)
    {
        
    }
    else
    {
          JOptionPane.showMessageDialog(null, "Mot de passe incorrecte veuillez saisir un mot de passe qui comptient plus de 8 caracteres","veuillez entrer un mot de passe valide",JOptionPane.INFORMATION_MESSAGE);
           PasswordEdit.requestFocus();
    }
    }//GEN-LAST:event_PasswordEditFocusLost

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
        MenuUtilisateur a=new MenuUtilisateur();
        a.setVisible(true); 
    }//GEN-LAST:event_jButton2MouseClicked
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutUtilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeEdit;
    private javax.swing.JButton AjoutButton;
    private javax.swing.JTextField EmailEdit;
    private javax.swing.JTextField LoginEdit;
    private javax.swing.JTextField NomEdit;
    private javax.swing.JPasswordField PasswordEdit;
    private javax.swing.JTextField PrenomEdit;
    private javax.swing.JButton ResetButton;
    private javax.swing.JLabel chemin;
    private javax.swing.JLabel cheminLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel varAge;
    private javax.swing.JLabel varLogin;
    private javax.swing.JLabel varMail;
    private javax.swing.JLabel varNom;
    private javax.swing.JLabel varPassword;
    private javax.swing.JLabel varPrenom;
    // End of variables declaration//GEN-END:variables
}
