/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.AdministrateurDAO;
import edu.esprit.dao.implementations.UtilisateurDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author esprit
 */
public class AjoutAdministrateur extends javax.swing.JFrame {
  String login;
  int id;
    /**
     * Creates new form AjoutAdmin
     */
    public AjoutAdministrateur() {
        
        initComponents();
    }

    public AjoutAdministrateur(String login, int id) {
        this.login = login;
        this.id = id;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        utilisateurComboBox = new javax.swing.JComboBox();
        ajouterButton = new javax.swing.JButton();
        retourButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1063, 737));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Espace Ajout Administrateur");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 520, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Selectionnez un utilisateur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 202, 27));

        utilisateurComboBox.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(utilisateurComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 178, -1));

        ajouterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ajouterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/ajouter-en-plus-icone-9315-48.png"))); // NOI18N
        ajouterButton.setContentAreaFilled(false);
        ajouterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ajouterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 110, -1));

        retourButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        retourButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        retourButton.setContentAreaFilled(false);
        retourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourButtonMouseClicked(evt);
            }
        });
        getContentPane().add(retourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 110, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Office-Customer-Male-Light-icon.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 50, 80));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Ajouter");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 80, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1063, 737));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1130, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                                    
       UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
       List<Utilisateur> resultat=utilisateurDAO.afficherUtilisateurs();
       for(Utilisateur utilisateur:resultat)
       {
           utilisateurComboBox.addItem(utilisateur.getLogin());
       }
    
    }//GEN-LAST:event_formWindowOpened

    private void ajouterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterButtonMouseClicked
        String nomUtilisateur=utilisateurComboBox.getSelectedItem().toString();
        AdministrateurDAO administrateurDAO=new AdministrateurDAO();
        if(administrateurDAO.ajouterAdministrateurByNom(nomUtilisateur))
         JOptionPane.showMessageDialog(rootPane,"utilisateur ajouté en tant qu'administrateur avec succès");
        else
        JOptionPane.showMessageDialog(rootPane,"erreur de l'ajout ");   
    }//GEN-LAST:event_ajouterButtonMouseClicked

    private void retourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourButtonMouseClicked
     this.setVisible(false);
     MenuAdministrateur m=new MenuAdministrateur(login,id);
     m.setVisible(true);
    }//GEN-LAST:event_retourButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutAdministrateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton retourButton;
    private javax.swing.JComboBox utilisateurComboBox;
    // End of variables declaration//GEN-END:variables
}
