/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Compagnie;
import edu.esprit.dao.entities.Lieu;
import edu.esprit.dao.entities.Recommandation;
import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.CompagnieDAO;
import edu.esprit.dao.implementations.LieuDAO;
import edu.esprit.dao.implementations.UtilisateurDAO;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author esprit
 */
public class AjoutRecommandation extends javax.swing.JFrame {
String nom="";
String adresse="";
final JComboBox nomJComboBox = new JComboBox();
final JComboBox adrJComboBox = new JComboBox();
String login="farouha";
int id=28;


    /**
     * Creates new form AjoutRec
     */
    public AjoutRecommandation() {
        initComponents();
        jTabbedPane1.setSelectedIndex(1);
       
    }
    
     public AjoutRecommandation(String login,int id) {
        initComponents();
        jTabbedPane1.setSelectedIndex(1);
        this.login=login;
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        adresseLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        ajouterButton = new javax.swing.JButton();
        quitterButton = new javax.swing.JButton();
        adrComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        AutreEdit = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionEdit = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NomLabel = new javax.swing.JLabel();
        DescriptionLabel = new javax.swing.JLabel();
        AjouterButton = new javax.swing.JButton();
        QuitterButton = new javax.swing.JButton();
        comboBoxNom = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        autreEdit = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        EditDescription = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1063, 737));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adresseLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        adresseLabel.setText("Adresse");
        jPanel3.add(adresseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 68, -1));

        descriptionLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        descriptionLabel.setText("Description");
        jPanel3.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 78, -1));

        ajouterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ajouterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/address-book-icon.png"))); // NOI18N
        ajouterButton.setContentAreaFilled(false);
        ajouterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterButtonMouseClicked(evt);
            }
        });
        ajouterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ajouterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        quitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        quitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        quitterButton.setContentAreaFilled(false);
        quitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitterButtonMouseClicked(evt);
            }
        });
        quitterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterButtonActionPerformed(evt);
            }
        });
        jPanel3.add(quitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, -1, -1));

        adrComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                adrComboBoxItemStateChanged(evt);
            }
        });
        jPanel3.add(adrComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 260, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Autres");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 60, -1));

        AutreEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel3.add(AutreEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 260, -1));

        descriptionEdit.setColumns(20);
        descriptionEdit.setRows(5);
        jScrollPane1.setViewportView(descriptionEdit);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 260, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Ajouter");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/backComp.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1063, 737));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 780));

        jTabbedPane1.addTab("Recommander un Lieu", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        NomLabel.setText("Nom");
        jPanel2.add(NomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 74, -1));

        DescriptionLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        DescriptionLabel.setText("Description");
        jPanel2.add(DescriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 104, -1));

        AjouterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        AjouterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/add-event-icon.png"))); // NOI18N
        AjouterButton.setContentAreaFilled(false);
        AjouterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AjouterButtonMouseClicked(evt);
            }
        });
        jPanel2.add(AjouterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        QuitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        QuitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        QuitterButton.setContentAreaFilled(false);
        QuitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterButtonMouseClicked(evt);
            }
        });
        jPanel2.add(QuitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, -1, -1));

        comboBoxNom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxNomItemStateChanged(evt);
            }
        });
        jPanel2.add(comboBoxNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 270, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Autres");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 70, -1));

        autreEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel2.add(autreEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 270, -1));

        EditDescription.setColumns(20);
        EditDescription.setRows(5);
        jScrollPane2.setViewportView(EditDescription);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 270, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Ajouter");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/backComp.jpg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1063, 737));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        jTabbedPane1.addTab("Recommander une Compagnie", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterButtonMouseClicked
        //String nom = comboBoxNom.getSelectedItem().toString();
        System.out.println(id);
        if (nom.equals("")) {
           String nomautre = autreEdit.getText();
            String description = EditDescription.getText(); 
            UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
            Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurById(id);
            Compagnie compagnie = new Compagnie(description,nomautre,1,utilisateur);
            CompagnieDAO compagnieDAO = new CompagnieDAO();
            if (compagnieDAO.ajouterCompagnie(compagnie)) {
                JOptionPane.showMessageDialog(rootPane, "compagnie ajoutée avec succès");
                autreEdit.setText(null);
                EditDescription.setText(null);
            } else {
                JOptionPane.showMessageDialog(rootPane, "compagnie non ajoutée");
            }
        } else {
            autreEdit.setEditable(false);
            String nomcombo=comboBoxNom.getSelectedItem().toString();
            String description = EditDescription.getText();     
            CompagnieDAO compagnieDAO = new CompagnieDAO();
             //int id=compagnieDAO.recupererId(nom);
            Compagnie cmp=compagnieDAO.rechercherCompagnieByNom(nomcombo);
            UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
            Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurById(id);
            System.out.println(id);
           Compagnie compagnie = new Compagnie(id,description,cmp.getNom(),cmp.getNombre()+1,utilisateur);
            if (compagnieDAO.modifierCompagnie(compagnie)) {
                JOptionPane.showMessageDialog(rootPane, "compagnie mise à jour avec succès");
            } else {
                JOptionPane.showMessageDialog(rootPane, "compagnie non mise à jour");
            }
        }
        comboBoxNom.removeAllItems();
         CompagnieDAO compagnieDAO = new CompagnieDAO();
        List<Compagnie> resultat = compagnieDAO.afficherCompagnies();
        comboBoxNom.addItem(null);
        for (Compagnie compagnie : resultat) {
            comboBoxNom.addItem(compagnie.getNom());
        }
        
          /*String description=EditDescription.getText();
          Compagnie compagnie = new Compagnie(nom, description,1);
          CompagnieDAO compagnieDAO = new CompagnieDAO();
            if (compagnieDAO.ajouterCompagnie(compagnie)) {
                JOptionPane.showMessageDialog(rootPane, "compagnie ajoutée avec succès");
            } else {
                JOptionPane.showMessageDialog(rootPane, "compagnie non ajoutée");
            }
          Compagnie cmp=compagnieDAO.rechercherCompagnieByNom(nom);   
          compagnie = new Compagnie(cmp.getId(),description,cmp.getNom(),cmp.getNombre()+1);
            if (compagnieDAO.modifierCompagnie(compagnie)) {
                JOptionPane.showMessageDialog(rootPane, "compagnie modifiée avec succès");
            } else {
                JOptionPane.showMessageDialog(rootPane, "compagnie non ajoutée");
            }*/
        
        
    }//GEN-LAST:event_AjouterButtonMouseClicked

    private void QuitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterButtonMouseClicked
        this.setVisible(false);
        MenuRecommandation menu = new MenuRecommandation();
        menu.setVisible(true);
    }//GEN-LAST:event_QuitterButtonMouseClicked

    private void ajouterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterButtonMouseClicked
        /*String adresse = adrComboBox.getSelectedItem().toString();
        if (adresse.equals("")) {
            adresse = AutreEdit.getText();
             String description = descriptionEdit.getText();
             LieuDAO lieuDAO = new LieuDAO();
        Lieu lieu = new Lieu(adresse, description, 1);
        if (lieuDAO.ajouterLieu(lieu)) {
            JOptionPane.showMessageDialog(rootPane, "lieu ajouté avec succès");
        } else {
            JOptionPane.showMessageDialog(rootPane, "lieu non ajouté");
        }
        }else{
            AutreEdit.setEditable(false);
        String description = descriptionEdit.getText();
        LieuDAO lieuDAO = new LieuDAO();  
        Lieu li=lieuDAO.rechercherLieuByAdresse(adresse); 
        Lieu lieu = new Lieu(li.getId(),description,li.getAdresse(),li.getNombre()+1);
        if (lieuDAO.modifierLieu(lieu)) {
            JOptionPane.showMessageDialog(rootPane, "lieu modifié avec succès");
        } else {
            JOptionPane.showMessageDialog(rootPane, "lieu non modifié");
               }
        }*/
        
        
            if (adresse.equals("")) {
           String adrautre = AutreEdit.getText();
            String description = descriptionEdit.getText(); 
            UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
            Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurById(id);
            Lieu lieu = new Lieu(description,adrautre,1,utilisateur);
            LieuDAO lieuDAO=new LieuDAO();
            if (lieuDAO.ajouterLieu(lieu)) {
                JOptionPane.showMessageDialog(rootPane, "lieu ajouté avec succès");
                 AutreEdit.setText(null);
                descriptionEdit.setText(null);
            } else {
                JOptionPane.showMessageDialog(rootPane, "lieu non ajouté");
            }
        } else {
            AutreEdit.setEditable(false);
            String adrcombo=adrComboBox.getSelectedItem().toString();
            String description = descriptionEdit.getText();     
             LieuDAO lieuDAO=new LieuDAO();
            Lieu l=lieuDAO.rechercherLieuByAdresse(adrcombo);
            int id=lieuDAO.recupererId(adresse);
             UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
            Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurById(id);
            Lieu lieu=new Lieu(id,description,l.getAdresse(),l.getNombre()+1,utilisateur);
            if (lieuDAO.modifierLieu(lieu)) {
                JOptionPane.showMessageDialog(rootPane, "lieu mis à jour avec succès");
            } else {
                JOptionPane.showMessageDialog(rootPane, "lieu non mis à jour");
            }
        }
            adrComboBox.removeAllItems();
        LieuDAO lieuDAO = new LieuDAO();
        List<Lieu> resultatlieu = lieuDAO.afficherLieu();
        adrComboBox.addItem(null);
        for (Lieu lieu : resultatlieu) {
            adrComboBox.addItem(lieu.getAdresse());
        }
    }//GEN-LAST:event_ajouterButtonMouseClicked

    private void quitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterButtonMouseClicked
        this.setVisible(false);
        AccueilUtilisateur menu = new AccueilUtilisateur(login,id);
        menu.setVisible(true);
    }//GEN-LAST:event_quitterButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CompagnieDAO compagnieDAO = new CompagnieDAO();
        List<Compagnie> resultat = compagnieDAO.afficherCompagnies();
        comboBoxNom.addItem(null);
        for (Compagnie compagnie : resultat) {
            comboBoxNom.addItem(compagnie.getNom());
        }

        LieuDAO lieuDAO = new LieuDAO();
        List<Lieu> resultatlieu = lieuDAO.afficherLieu();
        adrComboBox.addItem(null);
        for (Lieu lieu : resultatlieu) {
            adrComboBox.addItem(lieu.getAdresse());
        }
    }//GEN-LAST:event_formWindowOpened

    private void comboBoxNomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxNomItemStateChanged
 
    if(comboBoxNom.getSelectedItem()== null)
    {
        autreEdit.setEditable(true);
      
    }
    else
        autreEdit.setEditable(false);
    nom=autreEdit.getText();

    }//GEN-LAST:event_comboBoxNomItemStateChanged

    private void adrComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_adrComboBoxItemStateChanged
      
    if(adrComboBox.getSelectedItem()== null)
    {
        AutreEdit.setEditable(true);
      
    }
    else
        AutreEdit.setEditable(false);
    adresse=AutreEdit.getText();
    }//GEN-LAST:event_adrComboBoxItemStateChanged

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
    
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void quitterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutRecommandation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjouterButton;
    private javax.swing.JTextField AutreEdit;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JTextArea EditDescription;
    private javax.swing.JLabel NomLabel;
    private javax.swing.JButton QuitterButton;
    private javax.swing.JComboBox adrComboBox;
    private javax.swing.JLabel adresseLabel;
    private javax.swing.JButton ajouterButton;
    private javax.swing.JTextField autreEdit;
    private javax.swing.JComboBox comboBoxNom;
    private javax.swing.JTextArea descriptionEdit;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton quitterButton;
    // End of variables declaration//GEN-END:variables
}
