/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.FbConnect.Facebook;
import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.UtilisateurDAO;
//import java.net.PasswordAuthentication;
import java.util.Properties;
import javax.mail.Session;
import javax.swing.JOptionPane;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.MessagingException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;


/**
 *
 * @author esprit
 */
public class AuthentificationEssai extends javax.swing.JFrame {
public String login="";
public int id=0;
    /**
     * Creates new form AuthentificationEssai
     */
    public AuthentificationEssai() {
        initComponents();
    }
    
    public AuthentificationEssai(String login,int id) {
        initComponents();
        this.login=login;
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        nomField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        passwordFiled = new javax.swing.JPasswordField();
        connectButton = new javax.swing.JButton();
        quitterButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(599, 319));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Authentification", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nomLabel.setText("Nom d'utilisateur :");
        jPanel1.add(nomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        nomField.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel1.add(nomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 180, 30));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("Mot de passe :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        jPanel1.add(passwordFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 180, 30));

        connectButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        connectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Button-Ok-icon.png"))); // NOI18N
        connectButton.setText("Se connecter");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(connectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        quitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        quitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Button-Close-icon.png"))); // NOI18N
        quitterButton.setText("Quitter");
        quitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitterButtonMouseClicked(evt);
            }
        });
        jPanel1.add(quitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 110, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Espace Authentification");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 210, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Mot de passe oublié?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 150, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Emoticon-Realize-Shock-Forgot-icon.png"))); // NOI18N
        jButton1.setText("Récupérer mot de passe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/fbconnect.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/BestBack.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 910, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 800, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed

    String login=nomField.getText();
    String password=passwordFiled.getText();
    UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
    if(utilisateurDAO.authenitification(login, password) == true)
    { 
        JOptionPane.showMessageDialog(null,"Authentification effectuée avec succès");
        Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurByLogin(login);
        login=(String)utilisateur.getLogin();
        id=(int)utilisateur.getId();
        System.out.println(login+id);
        if(utilisateurDAO.estAdmin(login)==true)
        { this.setVisible(false);
          AccueilAdmin c=new AccueilAdmin(login,id);
           // ModificationProfil c=new ModificationProfil(login,id);
          c.setVisible(true);
        } else
        { this.setVisible(false);
           AccueilUtilisateur m =new AccueilUtilisateur(login,id);
        //ConsultationProfil m=new ConsultationProfil(login, id);
           m.setVisible(true);
        }  
    }
        else
        {
         JOptionPane.showMessageDialog(null,"Authentification non aboutie");
        }
    
    }//GEN-LAST:event_connectButtonActionPerformed

    private void quitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_quitterButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
        Utilisateur utilisateur=new Utilisateur();
        String login=nomField.getText();
        //String password=passwordFiled.getText();
        
        String email=utilisateurDAO.recupererEmailByLogin(login);
        String password=utilisateurDAO.recupererPasswordByLogin(login);
        
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.port", "465");
        
        Session session;
    session = Session.getDefaultInstance(props,
            new javax.mail.Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication()
                {
                    return new PasswordAuthentication("besttrip.esprittd@gmail.com","123456789best");
                }
                
            }
            
    );
    
    try{
            Message message = new MimeMessage(session);
           
            message.setFrom(new InternetAddress("ghaya.zarrouk@esprit.tn"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email)); //mel base
            message.setSubject("lost password");
            message.setText(password); //mel base
            Transport.send(message);
            
            JOptionPane.showMessageDialog(null, "Votre mot de passe vous a été envoyé sur votre adresse Mail");
            
        }catch(Exception e){
         
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Facebook.connecterFB();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthentificationEssai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthentificationEssai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthentificationEssai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthentificationEssai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthentificationEssai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton connectButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomField;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JPasswordField passwordFiled;
    private javax.swing.JButton quitterButton;
    // End of variables declaration//GEN-END:variables
}
