/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.implementations.PhotoDAO;
import edu.esprit.dao.implementations.VideoDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class DetailExperienceModSupp extends javax.swing.JFrame {
    int id_experience;
    int id_utilsateur;
    public DetailExperienceModSupp(int id_experience,int id_utilsateur) {
        this.id_experience = id_experience;
        this.id_utilsateur=id_utilsateur;
        initComponents();
        
    }
    /**
     * Creates new form SupprimerDetailExperience    /**
     * Creates new form SupprimerDetailExperience    /**
     * Creates new form SupprimerDetailExperience    /**
     * Creates new form SupprimerDetailExperience    /**
     * Creates new form SupprimerDetailExperience    /**
     * Creates new form SupprimerDetailExperience    /**
     * Creates new form SupprimerDetailExperience    /**
     * Creates new form SupprimerDetailExperience
     */
    
    
    public DetailExperienceModSupp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listphoto = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        vidListe = new javax.swing.JList();
        suppphoto = new javax.swing.JButton();
        modifphoto = new javax.swing.JButton();
        suppvid = new javax.swing.JButton();
        modifvid = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, -1, -1));

        listphoto.setModel(new listeModel(id_experience));
        listphoto.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listphotoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listphoto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, 180, 240));

        vidListe.setModel(new VideoListeModel(id_experience));
        jScrollPane2.setViewportView(vidListe);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 180, 240));

        suppphoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        suppphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/supprimer.png"))); // NOI18N
        suppphoto.setText("supprimer");
        suppphoto.setContentAreaFilled(false);
        suppphoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppphotoMouseClicked(evt);
            }
        });
        getContentPane().add(suppphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        modifphoto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modifphoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/modifier.png"))); // NOI18N
        modifphoto.setText("modifier");
        modifphoto.setContentAreaFilled(false);
        modifphoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifphotoMouseClicked(evt);
            }
        });
        getContentPane().add(modifphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        suppvid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        suppvid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/supprimer.png"))); // NOI18N
        suppvid.setText("supprimer");
        suppvid.setContentAreaFilled(false);
        suppvid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suppvidMouseClicked(evt);
            }
        });
        getContentPane().add(suppvid, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 350, -1, -1));

        modifvid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modifvid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/modifier.png"))); // NOI18N
        modifvid.setText("modifier");
        modifvid.setContentAreaFilled(false);
        getContentPane().add(modifvid, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 470, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("Détails Expérience");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suppphotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppphotoMouseClicked
        
        VideoDAO vidDAO=new VideoDAO();
        //PhotoDAO phDAO=new PhotoDAO();
        System.out.println(listeModel.id_photo);
        if(JOptionPane.showConfirmDialog(null,"Voulez vous vraiment supprimer?","suppression",0)==0)                           
            { vidDAO.suppVideo(listeModel.id_photo);}

        listphoto.setModel(new listeModel(id_experience));
    }//GEN-LAST:event_suppphotoMouseClicked

    private void listphotoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listphotoValueChanged
        
    }//GEN-LAST:event_listphotoValueChanged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        MenuChoixExperience affiche = new MenuChoixExperience(id_experience,id_utilsateur);
        affiche.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void suppvidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suppvidMouseClicked
      
        PhotoDAO phDAO=new PhotoDAO();
        System.out.println(VideoListeModel.idVideo);
        if(JOptionPane.showConfirmDialog(null,"Voulez vous vraiment supprimer?","suppression",0)==0)                           
            { phDAO.suppPhoto(VideoListeModel.idVideo);}

        vidListe.setModel(new VideoListeModel(id_experience));
    }//GEN-LAST:event_suppvidMouseClicked

    private void modifphotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifphotoMouseClicked
        ModifDetailExp md=new ModifDetailExp(listeModel.id_photo,id_experience,id_utilsateur);
        md.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modifphotoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailExperienceModSupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailExperienceModSupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailExperienceModSupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailExperienceModSupp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailExperienceModSupp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listphoto;
    private javax.swing.JButton modifphoto;
    private javax.swing.JButton modifvid;
    private javax.swing.JButton suppphoto;
    private javax.swing.JButton suppvid;
    private javax.swing.JList vidListe;
    // End of variables declaration//GEN-END:variables
}
