/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import com.sun.xml.internal.org.jvnet.mimepull.MIMEMessage;
import edu.esprit.dao.entities.Texte;
import edu.esprit.dao.technique.MyConnection;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.MessagingException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Toch
 */
public class EnvoiNewsletter extends javax.swing.JFrame {

    private URL url;
    String attach;
    private Connection cnx;
    /**
     * Creates new form EnvoiNewsletter
     */
    public EnvoiNewsletter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabelSubject = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        jLabelText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Text = new javax.swing.JTextArea();
        attachButton = new javax.swing.JButton();
        envoie = new javax.swing.JButton();
        path_attach = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Envoi Newsletter");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabelSubject.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSubject.setText("Objet :");
        getContentPane().add(jLabelSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 60, -1));
        getContentPane().add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 410, -1));

        jLabelText.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelText.setText("Text :");
        getContentPane().add(jLabelText, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 80, -1));

        Text.setColumns(20);
        Text.setRows(5);
        jScrollPane1.setViewportView(Text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 410, 160));

        attachButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/add-event-icon.png"))); // NOI18N
        attachButton.setContentAreaFilled(false);
        attachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButtonActionPerformed(evt);
            }
        });
        getContentPane().add(attachButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, -1));

        envoie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        envoie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/blue-mail-send-icon.png"))); // NOI18N
        envoie.setText("Envoyer");
        envoie.setContentAreaFilled(false);
        envoie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoieActionPerformed(evt);
            }
        });
        getContentPane().add(envoie, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 613, 190, 60));

        path_attach.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(path_attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, 320, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 640, 70, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void attachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        attach=f.getAbsolutePath();
        path_attach.setText(attach);
    }//GEN-LAST:event_attachButtonActionPerformed

    private void envoieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoieActionPerformed

        //String From = from.getText();
        //String To_add = To.getText();
        String Subject = subject.getText();
        String Text_contenu = Text.getText();
        List<String> listeAbonne=new ArrayList<String>();
        String liste="";
        String req="SELECT Email FROM utilisateur u INNER JOIN abonnee a ON u.Id = a.Id_utilisateur";
        try{
            cnx=MyConnection.getInstance();
            PreparedStatement ps = cnx.prepareStatement(req);
            ResultSet res=ps.executeQuery();
            while(res.next())
            {
                listeAbonne.add(res.getString("Email"));

            }

            for(String s:listeAbonne)
            {
                liste=liste+","+s;
            }

            Properties props = new Properties();
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.socketFactory.port", "465");
            props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.port", "465");

            Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                    @Override
                    protected PasswordAuthentication getPasswordAuthentication()
                    {
                        return new PasswordAuthentication("besttrip.esprittd@gmail.com","123456789best");
                    }

                }

            );
            try{
                Message message = new MimeMessage(session);

                //message.setFrom(new InternetAddress(From));
                message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(liste));
                message.setSubject(Subject);
                message.setText(Text_contenu);
                Transport.send(message);

                JOptionPane.showMessageDialog(null, "message envoyer");

            }catch(Exception e){

                JOptionPane.showMessageDialog(null, e);
            }

        }catch(SQLException ex){

            Logger.getLogger(EnvoiNewsletter.class.getName()).log(Level.SEVERE,null, ex);
        } catch (IOException ex) {
            Logger.getLogger(EnvoiNewsletter.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_envoieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         MenuNewsletter en=new MenuNewsletter();
        en.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnvoiNewsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnvoiNewsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnvoiNewsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnvoiNewsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnvoiNewsletter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Text;
    private javax.swing.JButton attachButton;
    private javax.swing.JButton envoie;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelSubject;
    private javax.swing.JLabel jLabelText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel path_attach;
    private javax.swing.JTextField subject;
    // End of variables declaration//GEN-END:variables
}
