/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.dao.graphics;

/**
 *
 * @author ACER
 */
public class MenuGuide extends javax.swing.JFrame {
String login;
int id;
    /**
     * Creates new form menu
     */
    public MenuGuide() {
        initComponents();
    }
    
      public MenuGuide(String login,int id) {
        initComponents();
        this.login=login;
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ajout = new javax.swing.JButton();
        afficher = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        Envoyer_le_guide_par_mail = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ajout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ajout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samsung\\Desktop\\img\\book-add-icon.png")); // NOI18N
        ajout.setText("Ajout guide");
        ajout.setContentAreaFilled(false);
        ajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutActionPerformed(evt);
            }
        });
        getContentPane().add(ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        afficher.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        afficher.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samsung\\Desktop\\img\\Archive-manage-icon.png")); // NOI18N
        afficher.setText("Manipulation guide");
        afficher.setContentAreaFilled(false);
        afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherActionPerformed(evt);
            }
        });
        getContentPane().add(afficher, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        supprimer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        supprimer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samsung\\Desktop\\img\\cancel-icon.png")); // NOI18N
        supprimer.setText("Supprimer guide");
        supprimer.setContentAreaFilled(false);
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, -1, -1));

        Envoyer_le_guide_par_mail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Envoyer_le_guide_par_mail.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samsung\\Desktop\\img\\mail-send-icon.png")); // NOI18N
        Envoyer_le_guide_par_mail.setText("Envoyer vos mail");
        Envoyer_le_guide_par_mail.setContentAreaFilled(false);
        Envoyer_le_guide_par_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Envoyer_le_guide_par_mailActionPerformed(evt);
            }
        });
        getContentPane().add(Envoyer_le_guide_par_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));

        jLabel2.setFont(new java.awt.Font("Moire ExtraBold", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("GUIDE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samsung\\Desktop\\img\\Address-Book-Mac-icon.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 670, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Samsung\\Desktop\\tt.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherActionPerformed
      AfficherGuide g = new AfficherGuide();
      MenuGuide m = new MenuGuide();
       g.setVisible(true);
       m.setVisible(false);
       
    }//GEN-LAST:event_afficherActionPerformed

    private void ajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutActionPerformed
     AjoutGuide g = new AjoutGuide(id,login);
       g.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_ajoutActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        SupprimerGuide g = new SupprimerGuide();
      MenuGuide m = new MenuGuide();
       g.setVisible(true);
       m.setVisible(false);
    }//GEN-LAST:event_supprimerActionPerformed

    private void Envoyer_le_guide_par_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Envoyer_le_guide_par_mailActionPerformed
       GuideMail g = new GuideMail();
      MenuGuide m = new MenuGuide();
       g.setVisible(true);
       m.setVisible(false);
    }//GEN-LAST:event_Envoyer_le_guide_par_mailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuUtilisateur m=new MenuUtilisateur(login,id);
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGuide().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Envoyer_le_guide_par_mail;
    private javax.swing.JButton afficher;
    private javax.swing.JButton ajout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton supprimer;
    // End of variables declaration//GEN-END:variables
}
