/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

/**
 *
 * @author esprit
 */
public class MenuUtilisateur extends javax.swing.JFrame {
private String login;
private int id;
    /**
     * Creates new form MenuUtilisateur
     */
    public MenuUtilisateur() {
        initComponents();
    }
    
     public MenuUtilisateur(String login,int id) {
        initComponents();
        this.login=login;
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ModifierButton = new javax.swing.JButton();
        AfficherButtun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        supprimerButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1063, 737));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ModifierButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ModifierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/profile-settings-icon.png"))); // NOI18N
        ModifierButton.setContentAreaFilled(false);
        ModifierButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ModifierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 90, 60));

        AfficherButtun.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        AfficherButtun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/profile-search-icon.png"))); // NOI18N
        AfficherButtun.setContentAreaFilled(false);
        AfficherButtun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AfficherButtunMouseClicked(evt);
            }
        });
        jPanel1.add(AfficherButtun, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Espace Utilisateur ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 350, 32));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/logout-icone-7871-64.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 110, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 11, -1, -1));

        supprimerButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        supprimerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/profile-delete-icon.png"))); // NOI18N
        supprimerButton.setContentAreaFilled(false);
        supprimerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerButtonMouseClicked(evt);
            }
        });
        jPanel1.add(supprimerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 170, 60));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Editer profil");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 90, 70));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Désactiver profil");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 140, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("consulter profil");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 120, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/tt.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1063, 737));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1020, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifierButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierButtonMouseClicked
        this.setVisible(false);
        ModificationProfil m=new ModificationProfil(login,id);
        m.setVisible(true);
    }//GEN-LAST:event_ModifierButtonMouseClicked

    private void AfficherButtunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AfficherButtunMouseClicked
        this.setVisible(false);
        ConsultationProfil m=new ConsultationProfil(login, id);
        m.setVisible(true);
    }//GEN-LAST:event_AfficherButtunMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
        Authentification a=new Authentification();
        a.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void supprimerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerButtonMouseClicked
         this.setVisible(false);
        DesactiverCompte m=new DesactiverCompte(login, id);
        m.setVisible(true);
    }//GEN-LAST:event_supprimerButtonMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
         this.setVisible(false);
        AccueilUtilisateur m=new AccueilUtilisateur(login, id);
        m.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AfficherButtun;
    private javax.swing.JButton ModifierButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton supprimerButton;
    // End of variables declaration//GEN-END:variables
}
