/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

/**
 *
 * @author esprit
 */
public class MenuRecommandation extends javax.swing.JFrame {
String login;
int id;
    /**
     * Creates new form MenRecommandation
     */
    public MenuRecommandation() {
        initComponents();
    }
    
     public MenuRecommandation(String login,int id) {
        initComponents();
        this.login=login;
        this.id=id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecCompagnie = new javax.swing.JButton();
        RecLieu = new javax.swing.JButton();
        quitterButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1063, 737));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RecCompagnie.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        RecCompagnie.setIcon(new javax.swing.ImageIcon("C:\\Users\\esprit\\Desktop\\pff\\add-event-icon.png")); // NOI18N
        RecCompagnie.setContentAreaFilled(false);
        RecCompagnie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecCompagnieMouseClicked(evt);
            }
        });
        getContentPane().add(RecCompagnie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 256, -1));

        RecLieu.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        RecLieu.setIcon(new javax.swing.ImageIcon("C:\\Users\\esprit\\Desktop\\pff\\Address-Book-icon.png")); // NOI18N
        RecLieu.setContentAreaFilled(false);
        RecLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecLieuMouseClicked(evt);
            }
        });
        getContentPane().add(RecLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 253, -1));

        quitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        quitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Button-Close-icon.png"))); // NOI18N
        quitterButton.setText("Quitter");
        quitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitterButtonMouseClicked(evt);
            }
        });
        getContentPane().add(quitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, 120, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setText("Menu recommandation");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 420, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Recommander une compagnie");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Recommander un lieu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/tt.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1063, 736));
        jLabel1.setPreferredSize(new java.awt.Dimension(1063, 736));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecCompagnieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecCompagnieMouseClicked
       this.setVisible(false);
        AjoutRecommandation ajout=new AjoutRecommandation();
        ajout.setVisible(true);
    }//GEN-LAST:event_RecCompagnieMouseClicked

    private void RecLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecLieuMouseClicked
       this.setVisible(false);
        AjoutRecommandation ajout=new AjoutRecommandation();
        ajout.setVisible(true);
    }//GEN-LAST:event_RecLieuMouseClicked

    private void quitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterButtonMouseClicked
      System.exit(0);
    }//GEN-LAST:event_quitterButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRecommandation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RecCompagnie;
    private javax.swing.JButton RecLieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton quitterButton;
    // End of variables declaration//GEN-END:variables
}
