/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.implementations.ExperiencesDAO;
import edu.esprit.dao.entities.Experience;

/**
 *
 * @author Samsung
 */
public class MenuChoixExperience extends javax.swing.JFrame {
   int id_experience;
   int id_utilisateur;
   
    public MenuChoixExperience() {
    }
    /**
     * Creates new form MenuChoixExperience    /**
     * Creates new form MenuChoixExperience    /**
     * Creates new form MenuChoixExperience    /**
     * Creates new form MenuChoixExperience
     */
   
    public MenuChoixExperience(int id_experience,int id_utilisateur) {
        this.id_utilisateur=id_utilisateur;
        this.id_experience = id_experience;
        ExperiencesDAO expDAO = new ExperiencesDAO();
        Experience exp = new Experience();
        exp = expDAO.cherchExperienceById(this.id_experience);
        initComponents();
        date.setEnabled(false);
        //date.getEditor().setEnabled(false);        
        date.setValue(exp.convtoDate(exp.getDate()));
        dep.setValue(exp.getDepense());
        titre_exp.setText(exp.getTitre());
        pays.setText(exp.getPays());
        type.setText(exp.getType());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consulter_tt_exp = new javax.swing.JButton();
        aj_exp = new javax.swing.JButton();
        Modifier_exp = new javax.swing.JButton();
        supp_exp = new javax.swing.JButton();
        retour = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        titre_exp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        dep = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        pays = new javax.swing.JTextField();
        type = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consulter_tt_exp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        consulter_tt_exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/Preview-icon.png"))); // NOI18N
        consulter_tt_exp.setText("Consulter Expérience");
        consulter_tt_exp.setContentAreaFilled(false);
        consulter_tt_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulter_tt_expActionPerformed(evt);
            }
        });
        getContentPane().add(consulter_tt_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 240, 70));

        aj_exp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        aj_exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/documents-folder-a-pen-to-write-icone-5211-64.png"))); // NOI18N
        aj_exp.setText("Ajouter Détails");
        aj_exp.setContentAreaFilled(false);
        aj_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aj_expActionPerformed(evt);
            }
        });
        getContentPane().add(aj_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 190, 80));

        Modifier_exp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Modifier_exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/modifier.png"))); // NOI18N
        Modifier_exp.setText("Modifier Expérience");
        Modifier_exp.setContentAreaFilled(false);
        Modifier_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifier_expActionPerformed(evt);
            }
        });
        getContentPane().add(Modifier_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 240, 50));

        supp_exp.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        supp_exp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/n.png"))); // NOI18N
        supp_exp.setText("Détails");
        supp_exp.setContentAreaFilled(false);
        supp_exp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supp_expMouseClicked(evt);
            }
        });
        supp_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supp_expActionPerformed(evt);
            }
        });
        getContentPane().add(supp_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 200, 70));

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        retour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retourMouseClicked(evt);
            }
        });
        getContentPane().add(retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Titre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        titre_exp.setEditable(false);
        titre_exp.setBackground(new java.awt.Color(255, 255, 255));
        titre_exp.setToolTipText("");
        titre_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titre_expActionPerformed(evt);
            }
        });
        getContentPane().add(titre_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Dépense");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        date.setModel(new javax.swing.SpinnerDateModel());
        date.setEnabled(false);
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 40, -1));

        dep.setEditable(false);
        dep.setBackground(new java.awt.Color(255, 255, 255));
        dep.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Pays");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));

        pays.setEditable(false);
        pays.setBackground(new java.awt.Color(255, 255, 255));
        pays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paysActionPerformed(evt);
            }
        });
        getContentPane().add(pays, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 150, 30));

        type.setEditable(false);
        type.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 190, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/tt.jpg"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Modifier_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifier_expActionPerformed
       ModifierExperienceMedia mexp=new ModifierExperienceMedia(this.id_experience,id_utilisateur);
       mexp.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_Modifier_expActionPerformed

    private void retourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retourMouseClicked
         AfficheExperience affiche= new AfficheExperience(id_utilisateur);
         affiche.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_retourMouseClicked

    private void consulter_tt_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulter_tt_expActionPerformed
           AffichagesDetailExperience a = new AffichagesDetailExperience(id_experience,id_utilisateur);                                                   
           a.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_consulter_tt_expActionPerformed

    private void aj_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aj_expActionPerformed
       AjoutMedia ajout = new AjoutMedia(id_experience,id_utilisateur);
       ajout.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_aj_expActionPerformed

    private void supp_expMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supp_expMouseClicked
       DetailExperienceModSupp suppDetail=new DetailExperienceModSupp(id_experience,id_utilisateur);
       suppDetail.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_supp_expMouseClicked

    private void titre_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titre_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titre_expActionPerformed

    private void supp_expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supp_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supp_expActionPerformed

    private void paysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paysActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuChoixExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuChoixExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuChoixExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuChoixExperience.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuChoixExperience().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Modifier_exp;
    private javax.swing.JButton aj_exp;
    private javax.swing.JLabel back;
    private javax.swing.JButton consulter_tt_exp;
    private javax.swing.JSpinner date;
    private javax.swing.JFormattedTextField dep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField pays;
    private javax.swing.JLabel retour;
    private javax.swing.JButton supp_exp;
    private javax.swing.JTextField titre_exp;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
