/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.implementations.ExperiencesDAO;
import edu.esprit.dao.entities.Experience;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class ModifierExperienceMedia extends javax.swing.JFrame {
  int id_experience;
  int id_utilsateur;
    public ModifierExperienceMedia(int id_experience,int id_utilsateur) {
        this.id_experience = id_experience;
        this.id_utilsateur=id_utilsateur;
        ExperiencesDAO expDAO=new ExperiencesDAO();
        Experience exp=new Experience();
        exp=expDAO.cherchExperienceById(this.id_experience);
       
        initComponents();
       date.setEnabled(true);
       
       //date.getEditor().setEnabled(false);
        titre.setText(exp.getTitre());        
        date.setValue(exp.convtoDate(exp.getDate()));
        dep.setValue(exp.getDepense());
        desc.setText(exp.getContenu());
        
        
    }
    /**
     * Creates new form ModifierExperienceMedia    /**
     * Creates new form ModifierExperienceMedia    /**
     * Creates new form ModifierExperienceMedia    /**
     * Creates new form ModifierExperienceMedia
     */
   
    public ModifierExperienceMedia() {
        initComponents();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        titre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        date = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        dep = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        modif = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Titre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));
        getContentPane().add(titre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 330, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 40, 20));

        date.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 330, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Dépense");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));
        getContentPane().add(dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 330, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, -1, -1));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 330, -1));

        modif.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/modifier.png"))); // NOI18N
        modif.setText("Modifier");
        modif.setContentAreaFilled(false);
        modif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifMouseClicked(evt);
            }
        });
        getContentPane().add(modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 150, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setText("Modifier Expérience");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 350, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifMouseClicked
        Experience exp=new Experience();
        ExperiencesDAO expDAO=new ExperiencesDAO();
        exp=expDAO.cherchExperienceById(id_experience);
        
        exp.setContenu(desc.getText());
        double d=(double) dep.getValue();
        exp.setDepense(d);
        exp.setTitre(titre.getText());
        System.out.println(exp);
        expDAO.modifExperience(exp);
        JOptionPane.showMessageDialog(rootPane, "Modification effectué");
        MenuChoixExperience menChoix=new MenuChoixExperience(id_experience,id_utilsateur);
        menChoix.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_modifMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
       MenuChoixExperience menChoix=new MenuChoixExperience(id_experience,id_utilsateur);
        menChoix.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierExperienceMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierExperienceMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierExperienceMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierExperienceMedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierExperienceMedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner date;
    private javax.swing.JFormattedTextField dep;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modif;
    private javax.swing.JTextField titre;
    // End of variables declaration//GEN-END:variables
}
