/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Compagnie;
import edu.esprit.dao.entities.Lieu;
import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.AdministrateurDAO;
import edu.esprit.dao.implementations.CompagnieDAO;
import edu.esprit.dao.implementations.LieuDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author esprit
 */
public class ModifierRecommandation extends javax.swing.JFrame {

    /**
     * Creates new form ModifierRecommandation
     */
    public ModifierRecommandation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        adresseEdit = new javax.swing.JLabel();
        adresseComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        ValiderButton = new javax.swing.JButton();
        QuitterButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        descriptionEdit = new javax.swing.JTextField();
        validerButton = new javax.swing.JButton();
        quitterButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adresseEdit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        adresseEdit.setText("Adresse du lieu");
        jPanel2.add(adresseEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 136, -1));

        adresseComboBox.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel2.add(adresseComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 270, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Ajouter une description");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 270, 100));

        ValiderButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ValiderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/modifier.png"))); // NOI18N
        ValiderButton.setText("Modifier");
        ValiderButton.setContentAreaFilled(false);
        ValiderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValiderButtonMouseClicked(evt);
            }
        });
        jPanel2.add(ValiderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 170, -1));

        QuitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        QuitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        QuitterButton.setContentAreaFilled(false);
        QuitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterButtonMouseClicked(evt);
            }
        });
        jPanel2.add(QuitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/backComp.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        jTabbedPane1.addTab("Modifier un lieu", jPanel2);

        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 619));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nom de la compagnie");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 156, -1));

        nomComboBox.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(nomComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 250, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Ajouter une description");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 171, -1));

        descriptionEdit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(descriptionEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 250, 70));

        validerButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        validerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/modifier.png"))); // NOI18N
        validerButton.setText("Modifier");
        validerButton.setContentAreaFilled(false);
        validerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validerButtonMouseClicked(evt);
            }
        });
        validerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(validerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 180, -1));

        quitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        quitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        quitterButton.setContentAreaFilled(false);
        quitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitterButtonMouseClicked(evt);
            }
        });
        jPanel1.add(quitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 47, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/backComp.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jTabbedPane1.addTab("Modifier une compagnie", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         CompagnieDAO compagnieDAO=new CompagnieDAO();
       List<Compagnie> resultat=compagnieDAO.afficherCompagnies();
       for(Compagnie compagnie:resultat)
       {
           nomComboBox.addItem(compagnie.getNom());
           descriptionEdit.setText(compagnie.getContenu());
       }
       LieuDAO lieuDAO=new LieuDAO();
       List<Lieu> resultatlieu=lieuDAO.afficherLieu();
       for(Lieu lieu:resultatlieu)
       {
           adresseComboBox.addItem(lieu.getAdresse());
           descriptionEdit.setText(lieu.getContenu());
       }
    }//GEN-LAST:event_formWindowOpened

    private void validerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validerButtonMouseClicked
          String nom=nomComboBox.getSelectedItem().toString();
          String description=descriptionEdit.getText();
          CompagnieDAO compagnieDAO=new CompagnieDAO();
          int id=compagnieDAO.recupererId(nom);
          Compagnie compagnie=new Compagnie(id,nom,description);
       if( compagnieDAO.modifierCompagnie(compagnie))
        JOptionPane.showMessageDialog(rootPane,"Modification effectuée");
       else 
         JOptionPane.showMessageDialog(rootPane,"Modification non effectuée");  
    }//GEN-LAST:event_validerButtonMouseClicked

    private void quitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterButtonMouseClicked
        this.setVisible(false);
        MenuRecommandation menu=new MenuRecommandation();
        menu.setVisible(true);
    }//GEN-LAST:event_quitterButtonMouseClicked

    private void ValiderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValiderButtonMouseClicked
        String adresse=adresseComboBox.getSelectedItem().toString();
          String description=descriptionEdit.getText();
        LieuDAO lieuDAO=new LieuDAO();
       int id=lieuDAO.recupererId(adresse);
           Lieu lieu=new Lieu(id,adresse,description);
       if( lieuDAO.modifierLieu(lieu))
        JOptionPane.showMessageDialog(rootPane,"Modification effectuée");
       else 
         JOptionPane.showMessageDialog(rootPane,"Modification non effectuée");  
    }//GEN-LAST:event_ValiderButtonMouseClicked

    private void QuitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterButtonMouseClicked
      this.setVisible(false);
        MenuRecommandation menu=new MenuRecommandation();
        menu.setVisible(true);
    }//GEN-LAST:event_QuitterButtonMouseClicked

    private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_validerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifierRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifierRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifierRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifierRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifierRecommandation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuitterButton;
    private javax.swing.JButton ValiderButton;
    private javax.swing.JComboBox adresseComboBox;
    private javax.swing.JLabel adresseEdit;
    private javax.swing.JTextField descriptionEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox nomComboBox;
    private javax.swing.JButton quitterButton;
    private javax.swing.JButton validerButton;
    // End of variables declaration//GEN-END:variables
}
