/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.UtilisateurDAO;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author esprit
 */
public class ModificationProfil extends javax.swing.JFrame {
public String myPath="";
public String login="";
int id;
    /**
     * Creates new form ModificationUtilisateur
     */
    public ModificationProfil() {
        initComponents();
    }
    
     public ModificationProfil(String login,int id) {
         
         this.id=id;
         this.login=login;
         UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
         Utilisateur utilisateur=utilisateurDAO.rechercherUtilisateurByLogin(login);
         initComponents();
         //System.out.println(utilisateur.getId());
         LoginEdit.setEditable(false);
         NomEdit.setText(utilisateur.getNom());
         PrenomEdit.setText(utilisateur.getPrenom());
         EmailEdit.setText(utilisateur.getMail());
         LoginEdit.setText(utilisateur.getLogin());
         PasswordEdit.setText(utilisateur.getPassword());
         AgeEdit.setText(Integer.toString(utilisateur.getAge()));
         //ImageIcon image = new ImageIcon(utilisateur.getImage());
        // ImageLabel.setIcon(image);
         ImageLabel.setText(utilisateur.getImage());
        
        myPath=utilisateur.getImage();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        varNom = new javax.swing.JLabel();
        varPrenom = new javax.swing.JLabel();
        varEmail = new javax.swing.JLabel();
        varLogin = new javax.swing.JLabel();
        varPassword = new javax.swing.JLabel();
        varAge = new javax.swing.JLabel();
        NomEdit = new javax.swing.JTextField();
        PrenomEdit = new javax.swing.JTextField();
        EmailEdit = new javax.swing.JTextField();
        LoginEdit = new javax.swing.JTextField();
        AgeEdit = new javax.swing.JTextField();
        ModifierButton = new javax.swing.JButton();
        QuitterButton = new javax.swing.JButton();
        PasswordEdit = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ImageLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(1063, 737));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Modification Profil");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 330, -1));

        varNom.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varNom.setText("Nom");
        jPanel1.add(varNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 76, -1));

        varPrenom.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varPrenom.setText("Prenom");
        jPanel1.add(varPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 76, -1));

        varEmail.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varEmail.setText("Email");
        jPanel1.add(varEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 76, -1));

        varLogin.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varLogin.setText("Login");
        jPanel1.add(varLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 76, -1));

        varPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varPassword.setText("Password");
        jPanel1.add(varPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 76, -1));

        varAge.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        varAge.setText("Age");
        jPanel1.add(varAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 76, -1));

        NomEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomEditKeyPressed(evt);
            }
        });
        jPanel1.add(NomEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 196, -1));

        PrenomEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PrenomEditKeyPressed(evt);
            }
        });
        jPanel1.add(PrenomEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 196, -1));

        EmailEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailEditFocusLost(evt);
            }
        });
        jPanel1.add(EmailEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 196, -1));

        LoginEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginEditKeyPressed(evt);
            }
        });
        jPanel1.add(LoginEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 196, -1));

        AgeEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AgeEditKeyPressed(evt);
            }
        });
        jPanel1.add(AgeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 40, -1));

        ModifierButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ModifierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/modifier.png"))); // NOI18N
        ModifierButton.setContentAreaFilled(false);
        ModifierButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ModifierButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 120, -1));

        QuitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        QuitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        QuitterButton.setContentAreaFilled(false);
        QuitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterButtonMouseClicked(evt);
            }
        });
        jPanel1.add(QuitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 110, -1));

        PasswordEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordEditFocusLost(evt);
            }
        });
        jPanel1.add(PasswordEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 196, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setLabelFor(jLabel4);
        jLabel4.setText("Choisir photo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 110, -1));

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton1.setText("choisir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, -1, -1));
        jPanel1.add(ImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 190, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Modifier");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 70, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterButtonMouseClicked
        this.setVisible(false);
         MenuUtilisateur m = new MenuUtilisateur(login,id);
          m.setVisible(true);
    }//GEN-LAST:event_QuitterButtonMouseClicked

    private void ModifierButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierButtonMouseClicked

        String prenom=PrenomEdit.getText();
        String email=EmailEdit.getText();
        String nom=NomEdit.getText();
        String password=PasswordEdit.getText();
        int age = Integer.parseInt(AgeEdit.getText());
        login=LoginEdit.getText();
        UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
        int id=utilisateurDAO.RecupererId(login);
        System.out.println(id);
        Utilisateur utilisateur=new Utilisateur(id,nom,prenom,email,login,password,age,myPath);
       if( utilisateurDAO.modifierUtilisateur(utilisateur))
       {JOptionPane.showMessageDialog(rootPane,"Modification effectuée");
        System.out.println(utilisateur.toString());}
       else 
         JOptionPane.showMessageDialog(rootPane,"Modification non effectuée");
    }//GEN-LAST:event_ModifierButtonMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
       List<Utilisateur> resultat=utilisateurDAO.afficherUtilisateurs();
       for(Utilisateur utilisateur:resultat)
       {
           nomBox.addItem(utilisateur.getLogin());
       } */
    }//GEN-LAST:event_formWindowOpened
  
    private void AgeEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeEditKeyPressed
                                
      char car= evt.getKeyChar();
        if((car<'0' || car>'9' ) && AgeEdit.getText().contains(".")
            && (car!=(char)KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulment numero","validation  "
                ,JOptionPane.INFORMATION_MESSAGE);
        } else if
        ((car<'0' ||car>'9')&&(car!='.')
            &&(car!=(char)KeyEvent.VK_BACK_SPACE)){
            evt.consume();
            JOptionPane.showMessageDialog(null,"veuiller n'introduire que des chiffres","message de confirmation d'ecrire seulment des chiffres "
                ,JOptionPane.INFORMATION_MESSAGE); }
                
    }//GEN-LAST:event_AgeEditKeyPressed

    private void NomEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomEditKeyPressed
     char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettres sont acceptées ","validation d'accepter des lettres"
                ,JOptionPane.INFORMATION_MESSAGE);
    }         
    }//GEN-LAST:event_NomEditKeyPressed

    private void PrenomEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrenomEditKeyPressed
         char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettres sont acceptées ","validation d'accepter des lettres"
                ,JOptionPane.INFORMATION_MESSAGE);
    }         
    }//GEN-LAST:event_PrenomEditKeyPressed

    private void LoginEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginEditKeyPressed
         char car= evt.getKeyChar();
        if((car<'a' || car>'z' ) && (car<'A' || car>'Z' )
            && (car!=(char)KeyEvent.VK_BACK_SPACE)&& (car!=(char)KeyEvent.VK_SPACE))
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"seulement les lettres sont acceptées ","validation d'accepter des lettres"
                ,JOptionPane.INFORMATION_MESSAGE);
    }         
    }//GEN-LAST:event_LoginEditKeyPressed
public boolean isEmail(String chaine)
    {Pattern pat=null;
     Matcher mat=null;    
    //pat=Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z](2,4)$");
    pat=Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
    mat=pat.matcher(chaine);
    if(mat.find())
    {
        return true;
    }
    else 
    {
        return false;
    }
    }
    
    
    
    
    
    
    private void PasswordEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordEditFocusLost
      if(PasswordEdit.getPassword().length >=8)
    {
        
    }
    else
    {
          JOptionPane.showMessageDialog(null, "Mot de passe incorrecte veuillez introduire un mot de passe qui contient plus de 8 caracteres","veuillez entrer un mot de passe valide",JOptionPane.INFORMATION_MESSAGE);
           PasswordEdit.requestFocus();
    }
    }//GEN-LAST:event_PasswordEditFocusLost

    private void EmailEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailEditFocusLost
    if(isEmail(EmailEdit.getText()))
       {
           
       }
       else
       {
           JOptionPane.showMessageDialog(null, "Email incorrecte veuillez entrer un mail valide","veuillez entrer un mail valide",JOptionPane.INFORMATION_MESSAGE);
           EmailEdit.requestFocus();
       }
    }//GEN-LAST:event_EmailEditFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int o=jFileChooser1.showOpenDialog(this);
        if(o==JFileChooser.APPROVE_OPTION)
        {
            File file=jFileChooser1.getSelectedFile();
            ImageIcon myImage = new ImageIcon(""+file);
            myPath=file.getAbsolutePath();
            String monchemin=file.getName();
            ImageLabel.setText(monchemin);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
                          
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificationProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificationProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificationProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificationProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificationProfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeEdit;
    private javax.swing.JTextField EmailEdit;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JTextField LoginEdit;
    private javax.swing.JButton ModifierButton;
    private javax.swing.JTextField NomEdit;
    private javax.swing.JPasswordField PasswordEdit;
    private javax.swing.JTextField PrenomEdit;
    private javax.swing.JButton QuitterButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel varAge;
    private javax.swing.JLabel varEmail;
    private javax.swing.JLabel varLogin;
    private javax.swing.JLabel varNom;
    private javax.swing.JLabel varPassword;
    private javax.swing.JLabel varPrenom;
    // End of variables declaration//GEN-END:variables
}
