/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Experience;
import edu.esprit.dao.entities.Video;
import edu.esprit.dao.implementations.ExperiencesDAO;
import edu.esprit.dao.implementations.VideoDAO;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Samsung
 */
public class ModifDetailExp extends javax.swing.JFrame {

    int idPhoto;
    int id_experience;
    File imageUpload;
    int id_utilisateur;
    String source;
    public ModifDetailExp(int idPhoto,int id_experience,int id_utilisateur) {
        this.idPhoto = idPhoto;
        this.id_experience=id_experience;
        this.id_utilisateur=id_utilisateur;
        
        initComponents();
        VideoDAO viDAO = new VideoDAO();
        Video vid = new Video();
        vid = viDAO.cherchVideoById(idPhoto);
        desc.setText(vid.getExtension());
        source=vid.getSource();
        Image img = Toolkit.getDefaultToolkit().getImage(vid.getSource());
        Image newimg = img.getScaledInstance(disp.getWidth(), disp.getHeight(), java.awt.Image.SCALE_SMOOTH);

        ImageIcon newIcon = new ImageIcon(newimg);
        disp.setIcon(newIcon);
        disp.setEnabled(true);
        disp.setDisabledIcon(newIcon);
        disp.setVisible(true);

    }

    /**
     * Creates new form AjoutDetailExp
     */

    public ModifDetailExp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        chooser = new javax.swing.JButton();
        disp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        modBut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Desciption");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 380, 140));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Photo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        chooser.setText("choisir fichier");
        chooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooserMouseClicked(evt);
            }
        });
        getContentPane().add(chooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));
        getContentPane().add(disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 220, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, -1, -1));

        modBut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        modBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/modifier.png"))); // NOI18N
        modBut.setText("Modifier");
        modBut.setContentAreaFilled(false);
        modBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modButMouseClicked(evt);
            }
        });
        getContentPane().add(modBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, 160, 60));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setText("Modifier Détail Expérience");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 460, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooserMouseClicked
      
        JFileChooser shooser = new JFileChooser();
        ImageFilter filtre = new ImageFilter();
        shooser.setFileFilter(filtre);
        shooser.setAcceptAllFileFilterUsed(false);
        shooser.showOpenDialog(null);
        imageUpload = shooser.getSelectedFile();

        Image img = Toolkit.getDefaultToolkit().getImage(imageUpload.getAbsolutePath());
        Image newimg = img.getScaledInstance(disp.getWidth(), disp.getHeight(), java.awt.Image.SCALE_SMOOTH);

        ImageIcon newIcon = new ImageIcon(newimg);
        disp.setIcon(newIcon);
        disp.setEnabled(true);

        disp.setDisabledIcon(newIcon);
        disp.setVisible(true);
        

    }//GEN-LAST:event_chooserMouseClicked

    private void modButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modButMouseClicked
       
        VideoDAO viDAO = new VideoDAO();
        Video vid = new Video();
        vid = viDAO.cherchVideoById(idPhoto);
        
        String description=desc.getText();
        source = imageUpload.getAbsolutePath();
        int taille = (int) imageUpload.length();
        
        vid.setSource(source);
        vid.setTaille(taille);
        vid.setExtension(description);
    
        viDAO.modifVideo(vid);
        
        JOptionPane.showMessageDialog(rootPane, "Modification effectué");
        disp.setVisible(false);
        desc.setText(null);
        DetailExperienceModSupp det=new DetailExperienceModSupp(id_experience,id_utilisateur);
        det.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modButMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
      DetailExperienceModSupp det=new DetailExperienceModSupp(id_experience,id_utilisateur);
        det.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifDetailExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifDetailExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifDetailExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifDetailExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifDetailExp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooser;
    private javax.swing.JTextArea desc;
    private javax.swing.JLabel disp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modBut;
    // End of variables declaration//GEN-END:variables
}
