/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.UtilisateurDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author esprit
 */
public class SuppressionUtilisateur extends javax.swing.JFrame {

    /**
     * Creates new form SuppressionUtilisateur
     */
    public SuppressionUtilisateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utilisateurLabel = new javax.swing.JLabel();
        utilisateurComboBox = new javax.swing.JComboBox();
        TitreLab = new javax.swing.JLabel();
        supprimerButton = new javax.swing.JButton();
        QuitterButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        utilisateurLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        utilisateurLabel.setText("choisissez un utilisateur");
        getContentPane().add(utilisateurLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 171, -1));

        getContentPane().add(utilisateurComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 178, -1));

        TitreLab.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        TitreLab.setText("Espace suppression utilisateur");
        getContentPane().add(TitreLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 530, -1));

        supprimerButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        supprimerButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\esprit\\Desktop\\bouton\\supprimer.png")); // NOI18N
        supprimerButton.setContentAreaFilled(false);
        supprimerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(supprimerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        QuitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        QuitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        QuitterButton.setContentAreaFilled(false);
        QuitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterButtonMouseClicked(evt);
            }
        });
        getContentPane().add(QuitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 120, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Supprimer");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1063, 737));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
       List<Utilisateur> resultat=utilisateurDAO.afficherUtilisateurs();
       for(Utilisateur utilisateur:resultat)
       {
           utilisateurComboBox.addItem(utilisateur.getLogin());
       }
    }//GEN-LAST:event_formWindowOpened

    private void supprimerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerButtonMouseClicked
     UtilisateurDAO utilisateurDAO=new UtilisateurDAO();
     String nom=utilisateurComboBox.getSelectedItem().toString();
    if( utilisateurDAO.supprimerUtilisateurByNom(nom))
       JOptionPane.showMessageDialog(rootPane,"utilisateur supprimé avec succès");
        else
     JOptionPane.showMessageDialog(rootPane,"erreur lors de la suppression");  
    }//GEN-LAST:event_supprimerButtonMouseClicked

    private void QuitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterButtonMouseClicked
         this.setVisible(false);
         MenuUtilisateur m = new MenuUtilisateur();
          m.setVisible(true);
    }//GEN-LAST:event_QuitterButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuppressionUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuppressionUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuppressionUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuppressionUtilisateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuppressionUtilisateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuitterButton;
    private javax.swing.JLabel TitreLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton supprimerButton;
    private javax.swing.JComboBox utilisateurComboBox;
    private javax.swing.JLabel utilisateurLabel;
    // End of variables declaration//GEN-END:variables
}
