/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Newsletter;
import edu.esprit.dao.implementations.NewsletterDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author zamama
 */
public class SuppressionNewsletter extends javax.swing.JFrame {

    /**
     * Creates new form supprimernewsletter
     */
    public SuppressionNewsletter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbNom = new javax.swing.JComboBox();
        buttonsup = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Supprimer Newsletter");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Nom Newsletter:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        cbNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomActionPerformed(evt);
            }
        });
        getContentPane().add(cbNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 200, -1));

        buttonsup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        buttonsup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/supprimer.png"))); // NOI18N
        buttonsup.setText("Supprimer");
        buttonsup.setContentAreaFilled(false);
        buttonsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsupActionPerformed(evt);
            }
        });
        getContentPane().add(buttonsup, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 705));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsupActionPerformed
 NewsletterDAO nDAO=new NewsletterDAO();
       String nom=cbNom.getSelectedItem().toString();
       nDAO.supprimerNewsletter(nom);
       JOptionPane.showMessageDialog(rootPane, "supprimée avec succés");
       this.setVisible(false); 
           SuppressionNewsletter a = new SuppressionNewsletter();
            a.setVisible(true);    }//GEN-LAST:event_buttonsupActionPerformed

    private void cbNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNomActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false); 
           MenuNewsletter a = new MenuNewsletter();
            a.setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

     private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
            NewsletterDAO newsletterDAO=new NewsletterDAO();
            List<Newsletter> maliste=new ArrayList<>();
            maliste=newsletterDAO.afficherNewsletters();
            
            for(Newsletter n:maliste)
            cbNom.addItem(n.getnom());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuppressionNewsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuppressionNewsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuppressionNewsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuppressionNewsletter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuppressionNewsletter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonsup;
    private javax.swing.JComboBox cbNom;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
