/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Compagnie;
import edu.esprit.dao.entities.Lieu;
import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.CompagnieDAO;
import edu.esprit.dao.implementations.LieuDAO;
import edu.esprit.dao.implementations.UtilisateurDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author esprit
 */
public class SupprimerRecommandation extends javax.swing.JFrame {

    /**
     * Creates new form supprimerRecommandation
     */
    public SupprimerRecommandation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        adresseLabel = new javax.swing.JLabel();
        lieuComboBox = new javax.swing.JComboBox();
        SupprimerButton = new javax.swing.JButton();
        QuitterButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nomLabel = new javax.swing.JLabel();
        compagnieComboBox = new javax.swing.JComboBox();
        supprimerButton = new javax.swing.JButton();
        quitterButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel2.setMinimumSize(new java.awt.Dimension(599, 349));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adresseLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        adresseLabel.setText("Adresse");
        jPanel2.add(adresseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 76, -1));

        jPanel2.add(lieuComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 290, 20));

        SupprimerButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        SupprimerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/supprimer.png"))); // NOI18N
        SupprimerButton.setText("Supprimer");
        SupprimerButton.setContentAreaFilled(false);
        SupprimerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupprimerButtonMouseClicked(evt);
            }
        });
        jPanel2.add(SupprimerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 170, -1));

        QuitterButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        QuitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        QuitterButton.setContentAreaFilled(false);
        QuitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterButtonMouseClicked(evt);
            }
        });
        QuitterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterButtonActionPerformed(evt);
            }
        });
        jPanel2.add(QuitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/backComp.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));

        jTabbedPane1.addTab("supprimer un lieu", jPanel2);

        jPanel1.setPreferredSize(new java.awt.Dimension(599, 349));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        nomLabel.setText("Nom de la compagnie");
        jPanel1.add(nomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 153, -1));

        compagnieComboBox.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(compagnieComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 290, 20));

        supprimerButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        supprimerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/supprimer.png"))); // NOI18N
        supprimerButton.setText("supprimer");
        supprimerButton.setContentAreaFilled(false);
        supprimerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerButtonMouseClicked(evt);
            }
        });
        jPanel1.add(supprimerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        quitterButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        quitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        quitterButton.setContentAreaFilled(false);
        quitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitterButtonMouseClicked(evt);
            }
        });
        jPanel1.add(quitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/backComp.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        jTabbedPane1.addTab("supprimer une compagnie", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 800, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       LieuDAO lieuDAO=new LieuDAO();
       List<Lieu> resultatlieu=lieuDAO.afficherLieu();
        for(Lieu lieu:resultatlieu)
       {
           lieuComboBox.addItem(lieu.getAdresse());
       }
       CompagnieDAO compagnieDAO=new CompagnieDAO();
       List<Compagnie> resultat=compagnieDAO.afficherCompagnies();
       for(Compagnie compagnie:resultat)
       {
           compagnieComboBox.addItem(compagnie.getNom());
       }
    }//GEN-LAST:event_formWindowOpened

    private void supprimerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerButtonMouseClicked
         CompagnieDAO compagnieDAO=new CompagnieDAO();
     String nom=compagnieComboBox.getSelectedItem().toString();
    if( compagnieDAO.supprimerCompagnieByNom(nom))
       JOptionPane.showMessageDialog(rootPane,"compagnie supprimée avec succès");
        else
     JOptionPane.showMessageDialog(rootPane,"erreur lors de la suppression");  
    }//GEN-LAST:event_supprimerButtonMouseClicked

    private void quitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterButtonMouseClicked
        this.setVisible(false);
        MenuRecommandation menu=new MenuRecommandation();
        menu.setVisible(true);
    }//GEN-LAST:event_quitterButtonMouseClicked

    private void SupprimerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimerButtonMouseClicked
         LieuDAO lieuDAO=new LieuDAO();
     String adresse=lieuComboBox.getSelectedItem().toString();
    if( lieuDAO.supprimerLieuByAdresse(adresse))
       JOptionPane.showMessageDialog(rootPane,"lieu supprimé avec succès");
        else
     JOptionPane.showMessageDialog(rootPane,"erreur lors de la suppression");  
    }//GEN-LAST:event_SupprimerButtonMouseClicked

    private void QuitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterButtonMouseClicked
       this.setVisible(false);
        MenuRecommandation menu=new MenuRecommandation();
        menu.setVisible(true);
    }//GEN-LAST:event_QuitterButtonMouseClicked

    private void QuitterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuitterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupprimerRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupprimerRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupprimerRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupprimerRecommandation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupprimerRecommandation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuitterButton;
    private javax.swing.JButton SupprimerButton;
    private javax.swing.JLabel adresseLabel;
    private javax.swing.JComboBox compagnieComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox lieuComboBox;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JButton quitterButton;
    private javax.swing.JButton supprimerButton;
    // End of variables declaration//GEN-END:variables
}
