/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.dao.graphics;

import edu.esprit.dao.entities.Utilisateur;
import edu.esprit.dao.implementations.AdministrateurDAO;
import edu.esprit.dao.implementations.UtilisateurDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author esprit
 */
public class SuppressionAdministrateur extends javax.swing.JFrame {

    /**
     * Creates new form SuppressionAdministrateur
     */
    public SuppressionAdministrateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        supprimerButton = new javax.swing.JButton();
        QuitterButton = new javax.swing.JButton();
        utilisateurLabel = new javax.swing.JLabel();
        utilisateurComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Espace Suppression ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 370, -1));

        supprimerButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        supprimerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/supprimer.png"))); // NOI18N
        supprimerButton.setBorderPainted(false);
        supprimerButton.setContentAreaFilled(false);
        supprimerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(supprimerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 587, 130, 70));

        QuitterButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        QuitterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/retourb.png"))); // NOI18N
        QuitterButton.setContentAreaFilled(false);
        QuitterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterButtonMouseClicked(evt);
            }
        });
        getContentPane().add(QuitterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, 110, -1));

        utilisateurLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        utilisateurLabel.setText("Nom d'utilisateur");
        getContentPane().add(utilisateurLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 136, -1));

        utilisateurComboBox.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        getContentPane().add(utilisateurComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 250, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Supprimer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 660, 110, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/dao/images/back.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(1063, 737));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 AdministrateurDAO adminsitrateurDAO=new AdministrateurDAO();
       List<Utilisateur> resultat=adminsitrateurDAO.afficherAdministrateurs();
       for(Utilisateur utilisateur:resultat)
       {
           utilisateurComboBox.addItem(utilisateur.getLogin());
       }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void supprimerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerButtonMouseClicked
    String utilisateur= utilisateurComboBox.getSelectedItem().toString();
    AdministrateurDAO adminsitrateurDAO=new AdministrateurDAO();
    if(adminsitrateurDAO.supprimerAdministrateurByNom(utilisateur))
        JOptionPane.showMessageDialog(rootPane,"administrateur supprimé avec succès");
        else
     JOptionPane.showMessageDialog(rootPane,"erreur lors de la suppression");  
    }//GEN-LAST:event_supprimerButtonMouseClicked

    private void QuitterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterButtonMouseClicked
      this.setVisible(false);
      MenuAdministrateur m=new MenuAdministrateur();
      m.setVisible(true);
    }//GEN-LAST:event_QuitterButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuppressionAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuppressionAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuppressionAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuppressionAdministrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuppressionAdministrateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton QuitterButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton supprimerButton;
    private javax.swing.JComboBox utilisateurComboBox;
    private javax.swing.JLabel utilisateurLabel;
    // End of variables declaration//GEN-END:variables
}
